### ISSUE TITLE
Just ride workouts are not being converted

### ISSUE THREAD

**Issue by anlesk** [philosowaffle/peloton-to-garmin#10]
I only have two Jist Ride workouts in peloton. When I run the script, I'm getting:

> 2019-12-12 09:50:41,028 - ERROR - peloton-to-garmin: Failed to write TCX file for workout a854899814b14b37bb3d1fd110f4180c - Exception: 'NoneType' object is not subscriptable

To fix that, I've changed the way ride details being pulled out of workout data:
`    totalTimeSeconds.text = str(workout["ride"]["duration"])
`
instead of
`    totalTimeSeconds.text = str(workout["peloton"]["ride"]["duration"])
`

As well as commenting out the whole logic around parsing instruction name. For some reason, that didn't work:
`if workout['ride']['instructor'] is not None:`
as workout actually has instructor:
`        "instructor": {
            "image_url": "https://s3.amazonaws.com/peloton-ride-images/just-ride.png",
            "name": "JUST RIDE"
        },`

**Comment by douglasawh** [comment]
@anlesk I'm confused. Are you saying that getting rid of ["peloton"] resolves the issue?

**Comment by anlesk** [comment]
@douglasawh exactly, that key is missing for Just Ride workouts.

**Comment by douglasawh** [comment]
@anlesk thanks!

For anyone else that comes across this issue, the file in question is tcx_builder.py which is in the libs directory.

**Comment by douglasawh** [comment]
getting rid of ["peloton"] in the totalTimeSeconds didn't work for me.

This is what I was confused about initially. Are you also saying you did the below?

#    instructor = ""
#    if workout['peloton']['ride']['instructor'] is not None:
#        instructor = " with " + workout['peloton']["ride"]["instructor"]["first_name"] + " " + workout['peloton']["ride"]["instructor"]["last_name"]

**Comment by philosowaffle** [comment]
This may have been addressed with #11 .  I included various fixes in that PR, one of which is handling most non-cycling activity types.  Checkout the latest `master` branch and let me know if its still an issue.

**Comment by douglasawh** [comment]
@philosowaffle 

I haven't spent much time with it, but new error, included below. I am not getting *any* files in the Output directory, so this might be something different.

```
dwhitfield@dwhitfield-ubuntu-alfresco:~/peloton-to-garmin-master$ python3 peloton-to-garmin.py
How many past activities do you want to grab?  2
2020-07-22 20:03:07,042 - INFO - peloton-to-garmin: Get latest 2 workouts.
2020-07-22 20:03:07,342 - INFO - peloton-to-garmin: Get workout: 88963f6daf89445387da4ee2e26015f9
2020-07-22 20:03:07,647 - INFO - peloton-to-garmin: Get workout samples
2020-07-22 20:03:08,007 - INFO - peloton-to-garmin: Get workout summary
Traceback (most recent call last):
  File "peloton-to-garmin.py", line 169, in <module>
    title, filename, garmin_activity_type = tcx_builder.workoutSamplesToTCX(workout, workoutSummary, workoutSamples, output_directory)
  File "/home/dwhitfield/peloton-to-garmin-master/lib/tcx_builder.py", line 53, in workoutSamplesToTCX
    fitness_discipline = workout["ride"]["fitness_discipline"]
KeyError: 'fitness_discipline'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "peloton-to-garmin.py", line 172, in <module>
    logger.error("Failed to write TCX file for workout {} - {} - Exception: {}".format(workoutId, e))
IndexError: Replacement index 2 out of range for positional args tuple
```

**Comment by philosowaffle** [comment]
Yeah, this looks like a separate issue, do you know what the activity types are of the 2 workouts its trying to grab? Might help me narrow down the issue.

**Comment by douglasawh** [comment]
@philosowaffle they are both just ride, but I get the same error when I try to grab 4.

**Comment by douglasawh** [comment]
@philosowaffle 

I will have to go back and test on ubuntu/python 3.8.2 again, but in centos/python 3.6.8, there is still obviously a problem with the Just Ride. 

To be clear, when you are talking about pulling master, you mean download https://github.com/philosowaffle/peloton-to-garmin/archive/master.zip, correct? Or did you mean to clone the repo? That I have not tried. I obviously have the new config file, so I am assuming I am grabbing what you suggested.

```
[centos@ip-10-250-75-75 12:26:41 peloton-to-garmin-master]$ python3 peloton-to-garmin.py
How many past activities do you want to grab?  4
2020-07-23 12:27:16,962 - INFO - peloton-to-garmin: Get latest 4 workouts.
2020-07-23 12:27:17,013 - INFO - peloton-to-garmin: Get workout: 88963f6daf89445387da4ee2e26015f9
2020-07-23 12:27:17,055 - INFO - peloton-to-garmin: Get workout samples
2020-07-23 12:27:17,145 - INFO - peloton-to-garmin: Get workout summary
2020-07-23 12:27:17,181 - ERROR - peloton-to-garmin.Tcx_Builder: Failed to Parse Activity Type, defaulting to 'Other' - Exception: 'fitness_discipline'
2020-07-23 12:27:17,181 - ERROR - peloton-to-garmin: Failed to write TCX file for workout 88963f6daf89445387da4ee2e26015f9 - Exception: 'NoneType' object is not subscriptable
2020-07-23 12:27:17,181 - INFO - peloton-to-garmin: Get workout: b776c61f3d7e4100a8a1136bc2e04352
2020-07-23 12:27:17,238 - INFO - peloton-to-garmin: Get workout samples
2020-07-23 12:27:17,310 - INFO - peloton-to-garmin: Get workout summary
2020-07-23 12:27:17,353 - ERROR - peloton-to-garmin.Tcx_Builder: Failed to Parse Activity Type, defaulting to 'Other' - Exception: 'fitness_discipline'
2020-07-23 12:27:17,353 - ERROR - peloton-to-garmin: Failed to write TCX file for workout b776c61f3d7e4100a8a1136bc2e04352 - Exception: 'NoneType' object is not subscriptable
2020-07-23 12:27:17,353 - INFO - peloton-to-garmin: Get workout: fb5f58969e3944509af21256f3459f52
2020-07-23 12:27:17,407 - INFO - peloton-to-garmin: Get workout samples
2020-07-23 12:27:17,705 - INFO - peloton-to-garmin: Get workout summary
2020-07-23 12:27:17,800 - INFO - peloton-to-garmin: Writing TCX file: 1594294667-30 min Power Zone Endurance Ride with Matt Wilpers-fb5f58969e3944509af21256f3459f52.tcx
2020-07-23 12:27:17,800 - INFO - peloton-to-garmin: Get workout: cf1a5803f70b4067afc0fc3813cfd012
2020-07-23 12:27:17,863 - INFO - peloton-to-garmin: Get workout samples
2020-07-23 12:27:18,007 - INFO - peloton-to-garmin: Get workout summary
2020-07-23 12:27:18,052 - INFO - peloton-to-garmin: Writing TCX file: 1594172074-10 min Sleep Meditation with Ross Rayburn-cf1a5803f70b4067afc0fc3813cfd012.tcx
2020-07-23 12:27:18,052 - INFO - peloton-to-garmin: Done!
2020-07-23 12:27:18,052 - INFO - peloton-to-garmin: Your Garmin TCX files can be found in the Output directory: Output
```

**Comment by douglasawh** [comment]
The work around does still work in the new version of the code (at least in python 3.6.8):

`[centos@ip-10-250-75-75 12:33:23 peloton-to-garmin-master]$ python3 peloton-to-garmin.py
How many past activities do you want to grab?  6
2020-07-23 12:33:34,625 - INFO - peloton-to-garmin: Get latest 6 workouts.
2020-07-23 12:33:34,688 - INFO - peloton-to-garmin: Get workout: 88963f6daf89445387da4ee2e26015f9
2020-07-23 12:33:34,727 - INFO - peloton-to-garmin: Get workout samples
2020-07-23 12:33:34,831 - INFO - peloton-to-garmin: Get workout summary
2020-07-23 12:33:34,867 - ERROR - peloton-to-garmin.Tcx_Builder: Failed to Parse Activity Type, defaulting to 'Other' - Exception: 'fitness_discipline'
2020-07-23 12:33:34,868 - INFO - peloton-to-garmin: Writing TCX file: 1595374979-27 sec Just Ride-88963f6daf89445387da4ee2e26015f9.tcx
2020-07-23 12:33:34,868 - INFO - peloton-to-garmin: Get workout: b776c61f3d7e4100a8a1136bc2e04352
2020-07-23 12:33:34,911 - INFO - peloton-to-garmin: Get workout samples
2020-07-23 12:33:35,068 - INFO - peloton-to-garmin: Get workout summary
2020-07-23 12:33:35,100 - ERROR - peloton-to-garmin.Tcx_Builder: Failed to Parse Activity Type, defaulting to 'Other' - Exception: 'fitness_discipline'
2020-07-23 12:33:35,102 - INFO - peloton-to-garmin: Writing TCX file: 1595370621-55 sec Just Ride-b776c61f3d7e4100a8a1136bc2e04352.tcx
2020-07-23 12:33:35,103 - INFO - peloton-to-garmin: Get workout: fb5f58969e3944509af21256f3459f52
2020-07-23 12:33:35,169 - INFO - peloton-to-garmin: Get workout samples
2020-07-23 12:33:35,445 - INFO - peloton-to-garmin: Get workout summary
2020-07-23 12:33:35,541 - INFO - peloton-to-garmin: Writing TCX file: 1594294667-30 min Power Zone Endurance Ride-fb5f58969e3944509af21256f3459f52.tcx
2020-07-23 12:33:35,541 - INFO - peloton-to-garmin: Get workout: cf1a5803f70b4067afc0fc3813cfd012
2020-07-23 12:33:35,595 - INFO - peloton-to-garmin: Get workout samples
2020-07-23 12:33:35,696 - INFO - peloton-to-garmin: Get workout summary
2020-07-23 12:33:35,744 - INFO - peloton-to-garmin: Writing TCX file: 1594172074-10 min Sleep Meditation-cf1a5803f70b4067afc0fc3813cfd012.tcx
2020-07-23 12:33:35,744 - INFO - peloton-to-garmin: Get workout: 6ef2208e50d24a738d5e1b41c5945dc9
2020-07-23 12:33:35,801 - INFO - peloton-to-garmin: Get workout samples
2020-07-23 12:33:35,991 - INFO - peloton-to-garmin: Get workout summary
2020-07-23 12:33:36,056 - INFO - peloton-to-garmin: Writing TCX file: 1593515816-10 min Low Impact Ride-6ef2208e50d24a738d5e1b41c5945dc9.tcx
2020-07-23 12:33:36,056 - INFO - peloton-to-garmin: Get workout: f34b284c743f48279e9d83b45c278ee1
2020-07-23 12:33:36,115 - INFO - peloton-to-garmin: Get workout samples
2020-07-23 12:33:36,249 - INFO - peloton-to-garmin: Get workout summary
2020-07-23 12:33:36,304 - INFO - peloton-to-garmin: Writing TCX file: 1593428461-20 min Metal Run-f34b284c743f48279e9d83b45c278ee1.tcx
2020-07-23 12:33:36,305 - INFO - peloton-to-garmin: Done!
2020-07-23 12:33:36,305 - INFO - peloton-to-garmin: Your Garmin TCX files can be found in the Output directory: Output`

**Comment by philosowaffle** [comment]
Yup, downloading the latest zip is just fine.  

If you have time to try one more thing, download the latest code again, in the config file you'll see a new value for `LogLevel`.  Set it to `DEBUG`.

Run the script one more time and paste the contents of the **log file** output here.  This will capture the actual data coming back from Peloton, it will help me not only apply the fix you mentioned but also add a test to prevent this from breaking in the future.

If the file is too big you may need to share via [gist](https://gist.github.com/).

**Comment by douglasawh** [comment]
idk how this is going to show up, but looks like drag-n-drop worked: [peloton-to-garmin.log](https://github.com/philosowaffle/peloton-to-garmin/files/4968523/peloton-to-garmin.log)

**Comment by philosowaffle** [comment]
Thanks @douglasawh that was perfect.  This issue should be fixed now.  Gonna close this ticket but feel free to open a new one if anyone continues to see issues.
