### ISSUE TITLE
Authentication Failure when Uploading to Garmin

### ISSUE THREAD

**Issue by grizzls** [philosowaffle/peloton-to-garmin#110]
I've just started getting these errors on V2

```
2021-05-17 12:57:07,243 [CRITICAL] Login Failure: Authentification failed.
[12:57:07 ERR] Failed to upload workouts. GUpload had exit code of 1
[12:57:07 ERR] Uncaught Exception.
Garmin.GarminUploadException: GUpload Exit Code: 1 - GUpload returned an error code. Failed to upload workouts.
   at Garmin.GarminUploader.UploadViaPython(String[] files) in /build/src/Garmin/GarminUploader.cs:line 111
   at Garmin.GarminUploader.UploadToGarmin() in /build/src/Garmin/GarminUploader.cs:line 50
   at PelotonToGarminConsole.Program.RunAsync(Configuration config) in /build/src/PelotonToGarminConsole/Program.cs:line 133
   at PelotonToGarminConsole.Program.Main(String[] args) in /build/src/PelotonToGarminConsole/Program.cs:line 93
Unhandled exception. Garmin.GarminUploadException: GUpload Exit Code: 1 - GUpload returned an error code. Failed to upload workouts.
   at Garmin.GarminUploader.UploadViaPython(String[] files) in /build/src/Garmin/GarminUploader.cs:line 111
   at Garmin.GarminUploader.UploadToGarmin() in /build/src/Garmin/GarminUploader.cs:line 50
   at PelotonToGarminConsole.Program.RunAsync(Configuration config) in /build/src/PelotonToGarminConsole/Program.cs:line 133
   at PelotonToGarminConsole.Program.Main(String[] args) in /build/src/PelotonToGarminConsole/Program.cs:line 93
```

**Comment by philosowaffle** [comment]
Merging with existing #109
