### ISSUE TITLE
Pace Metric Null causing double conversion exception in FIT Conversion

### ISSUE THREAD

**Issue by kenlpeters** [philosowaffle/peloton-to-garmin#111]
I tracked the null to double conversion issue to the Metric "Pace" in the values array the first few are null,null,null,null.  We should trap for that make then 0.0

GNU nano 3.2 log20210518.txt
2021-05-18 14:07:49.935 +00:00 [ERR] Uncaught Exception.
System.Text.Json.JsonException: The JSON value could not be converted to System.Double[]. Path: $.WorkoutS$ ---> System.InvalidOperationException: Cannot get the value of a token type 'Null' as a number.
 at System.Text.Json.Utf8JsonReader.TryGetDouble(Double& value)
 at System.Text.Json.Utf8JsonReader.GetDouble()
 at System.Text.Json.Serialization.Converters.DoubleConverter.Read(Utf8JsonReader& reader, Type typeToCo$ at System.Text.Json.Serialization.Converters.IEnumerableDefaultConverter`2.OnTryRead(Utf8JsonReader& re$ at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, J$ at System.Text.Json.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReade$ at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader,$ at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, J$ at System.Text.Json.Serialization.Converters.IEnumerableDefaultConverter`2.OnTryRead(Utf8JsonReader& re$ at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, J$ at System.Text.Json.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReade$ at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader,$ at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, J$ at System.Text.Json.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReade$ at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader,$ at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, J$ at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOption$ --- End of inner exception stack trace ---

**Comment by philosowaffle** [comment]
Alright, 

1. can you try changing your config in the [Format](https://github.com/philosowaffle/peloton-to-garmin/wiki/Configuration#format-config) section, set `"Json": true`, and `"SaveLocalCopy": true`.  
2. Run the program again
3. Look in the `output` folder, you should see a folder with the JSON workout, can you upload those files to this thread?

This will help me see the raw data coming back from Peloton and better handle this case.

**Comment by philosowaffle** [comment]
> I fixed this by making sure the config file was in the proper folder :)

Unrelated question from the other thread. Was the correct folder `src/PelotonToGarminConsole`? Just want to confirm because it seems I may be missing this step from the Wiki.  Want to make sure I update it correctly.

**Comment by kenlpeters** [comment]
Yes I had to move the configuration.local.json to src/PelotonToGarminConsole

**Comment by kenlpeters** [comment]
Had to zip it.. 

[98c617d5c56f4f1ab6fc250afc9aea5f_workout.zip](https://github.com/philosowaffle/peloton-to-garmin/files/6502468/98c617d5c56f4f1ab6fc250afc9aea5f_workout.zip)

**Comment by philosowaffle** [comment]
Thanks, probably won't be able to fix it till after work today.

**Comment by kenlpeters** [comment]
No worries.  If I can get the FIT to work I have work around for the authentication issue for now.  I am just manually uploading the file through connect.garmin.com.

**Comment by philosowaffle** [comment]
Took a stab at this and think I have it fixed on the latest version of v2 branch. I was able to successfully convert and manually upload the sample workout on my test account.

Give it a go and let me know if it works for you also.

**Comment by kenlpeters** [comment]
How do I update my version? Sorry for being a dunce

**Comment by kenlpeters** [comment]
Figured it out and it is working like a charm.  Now I need to to tie it into my NodeJS server and figure out a way to copy the output file to my iCloud Drive so I can upload the file from iPad.

**Comment by kenlpeters** [comment]
Never mind that request too I figured that out.  Day of quick learning.
