### ISSUE TITLE
Failure to convert workout V2 (Fit) - Stretching - No HR

### ISSUE THREAD

**Issue by kenlpeters** [philosowaffle/peloton-to-garmin#113]
I converted a stretch and I got this error. I was not wearing my HR monitor. Looks like it does not like null heart rates.

Peloton To Garmin
[22:20:32 ERR] Failed to convert workout data be6bf276b7464dff917f9e56260d42e7_5_min_Lower_Body_Stretch_with_Jess_Sims ./working/downloaded/be6bf276b7464dff917f9e56260d42e7_5_min_Lower_Body_Stretch_with_Jess_Sims.json
System.InvalidOperationException: Nullable object must have a value.
   at System.Nullable`1.get_Value()
   at Conversion.Converter`1.GetUserMaxHeartRate(WorkoutSamples workoutSamples) in /home/kpeters/peloton-ken/peloton-to-garmin-2/src/Conversion/IConverter.cs:line 317
   at Conversion.FitConverter.Convert(Workout workout, WorkoutSamples workoutSamples, WorkoutSummary workoutSummary) in /home/kpeters/peloton-ken/peloton-to-garmin-2/src/Conversion/FitConverter.cs:line 103
   at Conversion.Converter`1.Convert(String format) in /home/kpeters/peloton-ken/peloton-to-garmin-2/src/Conversion/IConverter.cs:line 94

**Comment by philosowaffle** [comment]
Fix pushed.
