### ISSUE TITLE
Uncaught Exception. System.ComponentModel.Win32Exception (2): The system cannot find the file specified.

### ISSUE THREAD

**Issue by DarthBookster** [philosowaffle/peloton-to-garmin#119]
Hello all. Trying to get this work on a new account and getting the error below. I went and reinstalled the newest Python and .Net 

I feel like maybe I need to add a directory to Path but not sure which.
Thanks for any help.

--------------------------------------------------------------------------------------------------------------------------------

2021-06-15 12:07:56.617 -05:00 [INF] Beginning Garmin Upload.
2021-06-15 12:07:56.622 -05:00 [FTL] Uncaught Exception.
System.ComponentModel.Win32Exception (2): The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Garmin.GarminUploader.UploadViaPython(String[] files) in /home/runner/work/peloton-to-garmin/peloton-to-garmin/src/Garmin/GarminUploader.cs:line 101
   at Garmin.GarminUploader.UploadToGarmin() in /home/runner/work/peloton-to-garmin/peloton-to-garmin/src/Garmin/GarminUploader.cs:line 54
   at PelotonToGarminConsole.Program.RunAsync(Configuration config)
   at PelotonToGarminConsole.Program.Main(String[] args)

**Comment by philosowaffle** [comment]
Are you using the windows exe?  If so I put a fix in for this error yesterday, can download that exe here: https://github.com/philosowaffle/peloton-to-garmin/releases/tag/v2.0.1

**Comment by Vicore1** [comment]
I am using v2.0.1 (windows exe) and an still getting the same error as 2.0 Also and chance getting the container version of 2.0 able on a raspberry pi?

**Comment by DarthBookster** [comment]
Yes this is on windows 10 64bit but this is from user error on my side. I misread the instructions and had set this to true.
   "PythonAndGUploadInstalled": false

I went ahead and redownloaded this new version and compared the 2 configuration files side by side and caught it. 

my apologies and thanks!

**Comment by philosowaffle** [comment]
@Vicore1 can you also double check your config file has:

```
"PythonAndGUploadInstalled": false
```

I'm currently running version 2 docker on my raspberry pi 4 which is arm64 architecture. Do you need arm32?

**Comment by Vicore1** [comment]
I have a pi 4 let me give it a shot. I am still getting the same error, I confirmed I have the false flag set for PythonAndGUploadInstalled. I am going to remove and start fresh just to make sure I didn't bork something.

**Comment by philosowaffle** [comment]
If you switch to the docker build then `"PythonAndGUploadInstalled": true`

Its confusing, I know, but it was a hack to support a single windows exe for those who don't want to mess with the command line.

Basically windows exe set  `"PythonAndGUploadInstalled": false`
All other cases set  `"PythonAndGUploadInstalled": true`

**Comment by rymanmal1** [comment]
System.ComponentModel.Win32Exception (2): The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Garmin.GarminUploader.UploadViaPython(String[] files) in /home/runner/work/peloton-to-garmin/peloton-to-garmin/src/Garmin/GarminUploader.cs:line 101
   at Garmin.GarminUploader.UploadToGarmin() in /home/runner/work/peloton-to-garmin/peloton-to-garmin/src/Garmin/GarminUploader.cs:line 54
   at PelotonToGarminConsole.Program.RunAsync(Configuration config)
   at PelotonToGarminConsole.Program.Main(String[] args)

Getting the same error on a fresh download of the program. My config file is set up as so:

{
  // Config Documentation: https://github.com/philosowaffle/peloton-to-garmin/wiki/Configuration
  "App": {
    "OutputDirectory": "./output",
    "WorkingDirectory": "./working",
    "SyncHistoryDbPath": "./output/syncHistory.json",
    "EnablePolling": true,
    "PollingIntervalSeconds": 86400,
    "PythonAndGUploadInstalled": false
  },

**Comment by rymanmal1** [comment]
I'm running it as the windows exe and I am using version 2.0.1. Let me know if I can provide any more information you might need.

**Comment by philosowaffle** [comment]
Can one of y'all still seeing this error [switch logging](https://github.com/philosowaffle/peloton-to-garmin/blob/master/configuration.example.json#L50) to `"Debug"` and post the log output?

I'm not able to reproduce on my end so definitely need to try to grab some more info to see what the difference is.

**Comment by rymanmal1** [comment]
So just switch "Information" to "debug"? I get this output log when I do that, which I believe is the same output as before. 


2021-06-16 19:07:40.171 -04:00 [INF] Beginning Garmin Upload.
2021-06-16 19:07:40.175 -04:00 [FTL] Uncaught Exception.
System.ComponentModel.Win32Exception (2): The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Garmin.GarminUploader.UploadViaPython(String[] files) in /home/runner/work/peloton-to-garmin/peloton-to-garmin/src/Garmin/GarminUploader.cs:line 101
   at Garmin.GarminUploader.UploadToGarmin() in /home/runner/work/peloton-to-garmin/peloton-to-garmin/src/Garmin/GarminUploader.cs:line 54
   at PelotonToGarminConsole.Program.RunAsync(Configuration config)
   at PelotonToGarminConsole.Program.Main(String[] args)

**Comment by rymanmal1** [comment]
Re-imported it and this is what was in the log. 

[20:03:57 DBG] Uploading to Garmin with the following parameters: C:\Users\ALICE\Downloads\win10-x64_2.0.1\python\upload\upload.exe -ge **email** -gp **password** -f "C:\XXXXX\XXXXX\Downloads\win10-x64_2.0.1\working\upload\0c864b97a7824e31999408e007cc7140_45_min_Power_Zone_Endurance_Ride_with_Ben_Alldis.fit" 
[20:03:57 FTL] Uncaught Exception.
System.ComponentModel.Win32Exception (2): The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Garmin.GarminUploader.UploadViaPython(String[] files) in /home/runner/work/peloton-to-garmin/peloton-to-garmin/src/Garmin/GarminUploader.cs:line 101
   at Garmin.GarminUploader.UploadToGarmin() in /home/runner/work/peloton-to-garmin/peloton-to-garmin/src/Garmin/GarminUploader.cs:line 54
   at PelotonToGarminConsole.Program.RunAsync(Configuration config)

**Comment by philosowaffle** [comment]
Sanity check, can you verify this path exists: `C:\XXXXXX\XXXXXX\Downloads\win10-x64_2.0.1\python\upload\upload.exe`?

Typically this error means it failed to find that `upload.exe` file.

**Comment by rymanmal1** [comment]
It does not exist in my folder.

**Comment by philosowaffle** [comment]
Oh, dang, I see the issue. One sec, let me fix it.

**Comment by rymanmal1** [comment]
Awesome! 5 coffees on me 🤙

**Comment by philosowaffle** [comment]
Appreciate that!

Ok, download the exe again from [here](https://github.com/philosowaffle/peloton-to-garmin/releases/tag/v2.0.1), I just updated it with the correct build.

I did something silly the first time I fixed this bug, I only fixed it in one of my build scripts, but completely forgot to fix it in the release script.

**Comment by rymanmal1** [comment]
Didnt work but it made more progress then the previous run. New log below. 


2021-06-16 20:27:30.587 -04:00 [ERR] Failed to upload workouts. GUpload had exit code of 1
2021-06-16 20:27:30.588 -04:00 [ERR] GUpload returned an error code. Failed to upload workouts.
Garmin.GarminUploadException: GUpload Exit Code: 1 - GUpload returned an error code. Failed to upload workouts.
   at Garmin.GarminUploader.UploadViaPython(String[] files) in D:\a\peloton-to-garmin\peloton-to-garmin\src\Garmin\GarminUploader.cs:line 117
   at Garmin.GarminUploader.UploadToGarmin() in D:\a\peloton-to-garmin\peloton-to-garmin\src\Garmin\GarminUploader.cs:line 54
   at PelotonToGarminConsole.Program.RunAsync(Configuration config)
2021-06-16 20:27:30.601 -04:00 [WRN] GUpload failed to upload files. You can find the converted files at ./output 
 You can manually upload your files to Garmin Connect, or wait for P2G to try again on the next sync job.
2021-06-16 20:27:30.602 -04:00 [INF] Sleeping for 86400 seconds...

**Comment by philosowaffle** [comment]
If you switch the log back to debug I suspect you will see output similar to:

```
[19:31:22 DBG] Uploading to Garmin with the following parameters: gupload -u **email** -p **password** "./working\upload\52cd0bbffeb04dfd80581a37709e1487_45_min_2000s_Ride_with_Kendall_Toole.fit"
[19:31:23 DBG] Error: Invalid credentials

[19:31:23 INF] GUpload: 2021-06-16 19:31:23,261 [INFO] Try to login on GarminConnect...
2021-06-16 19:31:23,936 [CRITICAL] Login Failure: Authentification failed.

[19:31:23 ERR] Failed to upload workouts. GUpload had exit code of 1
[19:31:24 ERR] GUpload returned an error code. Failed to upload workouts.
Garmin.GarminUploadException: GUpload Exit Code: 1 - GUpload returned an error code. Failed to upload workouts.
```

This is what I get on my machine, and is related to the [ongoing auth issues](https://github.com/philosowaffle/peloton-to-garmin/issues/109) a lot of folks are facing.

**Comment by rymanmal1** [comment]
Yep same error! Thanks for your help on this though! I'll keep my eyes peeled for any future updated on this 😸
