### ISSUE TITLE
Failed to convert workout data - GetHeartRateZone - Missing Heart Rate Zone Info

### ISSUE THREAD

**Issue by minh369** [philosowaffle/peloton-to-garmin#127]
When I try to run the program I get the following output:

Failed to convert workout data 7798a86c599a4e06921bfd9595f3564e_30_min_Latin_Celebration_Ride_with_Olivia_Amato ./working/downloaded/7798a86c599a4e06921bfd9595f3564e_30_min_Latin_Celebration_Ride_with_Olivia_Amato.json
System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Conversion.Converter`1.GetHeartRateZone(Int32 zone, WorkoutSamples workoutSamples) in /Users/Minh/Documents/peloton-to-garmin-master/src/Conversion/IConverter.cs:line 326
   at Conversion.Converter`1.GetUserMaxHeartRate(WorkoutSamples workoutSamples) in /Users/Minh/Documents/peloton-to-garmin-master/src/Conversion/IConverter.cs:line 315
   at Conversion.FitConverter.Convert(Workout workout, WorkoutSamples workoutSamples, WorkoutSummary workoutSummary) in /Users/Minh/Documents/peloton-to-garmin-master/src/Conversion/FitConverter.cs:line 103
   at Conversion.Converter`1.Convert(String format) in /Users/Minh/Documents/peloton-to-garmin-master/src/Conversion/IConverter.cs:line 94

**Comment by philosowaffle** [comment]
```
./working/downloaded/7798a86c599a4e06921bfd9595f3564e_30_min_Latin_Celebration_Ride_with_Olivia_Amato.json
```

Can you see if this file exists and if so attach it to this issue so I can see what data is causing the problem?

Also, please fill out this information from the Issue Template:

OS: [mac, linux, windows]
Method: [source, exe, docker]
Version: [1.2.0, 2.0.1, etc.]

**Comment by minh369** [comment]
OS: mac
Method: source
Version: 2

I couldn't upload the .json file so I copied pasted it into an odt file

[7798a86c599a4e06921bfd9595f3564e_30_min_Latin_Celebration_Ride_with_Olivia_Amato7798a86c599a4e06921bfd9595f3564e_30_min_Latin_Celebration_Ride_with_Olivia_Amato.odt](https://github.com/philosowaffle/peloton-to-garmin/files/6688239/7798a86c599a4e06921bfd9595f3564e_30_min_Latin_Celebration_Ride_with_Olivia_Amato7798a86c599a4e06921bfd9595f3564e_30_min_Latin_Celebration_Ride_with_Olivia_Amato.odt)

**Comment by philosowaffle** [comment]
Thanks! Think I've got a fix. Can you switch to branch `issue/127` and verify its working now for you?

**Comment by minh369** [comment]
Works like a charm! thank you!
