### ISSUE TITLE
Peloton 401 Not Authorized 

### ISSUE THREAD

**Issue by SpaceDA** [philosowaffle/peloton-to-garmin#196]
Has anyone else seen this with the Peloton API? Am using docker to run the app..

```
18:48:41 ERR] Http Call Failed. Unauthorized {"status":401,"error_code":3010,"subcode":null,"message":"Login failed","details":null}

[18:48:41 FTL] Failed to authenticate with Peloton.

Flurl.Http.FlurlHttpException: Call failed with status code 401 (Unauthorized): POST https://api.onepeloton.com/auth/login

   at Flurl.Http.FlurlRequest.HandleExceptionAsync(FlurlCall call, Exception ex, CancellationToken token)

   at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption)

   at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption)

   at Flurl.Http.ResponseExtensions.ReceiveJson[T](Task`1 response)

   at Peloton.ApiClient.InitAuthAsync(String overrideUserAgent) in /build/src/Peloton/ApiClient.cs:line 54

[18:48:41 INF] No download directory found. Nothing to do. ./working/downloaded
```

**Comment by SpaceDA** [comment]
> Has anyone else seen this with the Peloton API? Am using docker to run the app..
> 
> 
> 
> ```
> 
> 18:48:41 ERR] Http Call Failed. Unauthorized {"status":401,"error_code":3010,"subcode":null,"message":"Login failed","details":null}
> 
> 
> 
> [18:48:41 FTL] Failed to authenticate with Peloton.
> 
> 
> 
> Flurl.Http.FlurlHttpException: Call failed with status code 401 (Unauthorized): POST https://api.onepeloton.com/auth/login
> 
> 
> 
>    at Flurl.Http.FlurlRequest.HandleExceptionAsync(FlurlCall call, Exception ex, CancellationToken token)
> 
> 
> 
>    at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption)
> 
> 
> 
>    at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption)
> 
> 
> 
>    at Flurl.Http.ResponseExtensions.ReceiveJson[T](Task`1 response)
> 
> 
> 
>    at Peloton.ApiClient.InitAuthAsync(String overrideUserAgent) in /build/src/Peloton/ApiClient.cs:line 54
> 
> 
> 
> [18:48:41 INF] No download directory found. Nothing to do. ./working/downloaded
> 
> ```

Username and pw are correct in the config file.

**Comment by philosowaffle** [comment]
Please fill out an [issue template](https://github.com/philosowaffle/peloton-to-garmin/tree/master/.github/ISSUE_TEMPLATE) so folks can help most efficiently.

**Comment by SpaceDA** [comment]
Sorry, bad issue. Figured it out. I didn't properly build the docker image with my config file.
