### ISSUE TITLE
[Question] Docker instructions seem to be missing some steps

### ISSUE THREAD

**Issue by law** [philosowaffle/peloton-to-garmin#210]
Consider checking out the [discussion forum](https://github.com/philosowaffle/peloton-to-garmin/discussions) to get help from the community.  Or fill out this template to get help here.

**Problem**
Followed the Docker install instructions, cloned the repo, and have a `configuration.local.json` file in the repo-root.  `docker-compose up` (not listed in the instructions) fails with `FileNotFoundError: [Errno 2] No such file or directory` referencing `File "docker/transport/unixconn.py", line 43, in connect` (among others).  Is there a `docker build` step that needs to be run or something?  I see the docker-compose file referencing the public Docker-hub container, so I wouldn't think so, but the instructions are quite unclear on how to actually get the app running once `configuration.local.json` is created.  

**Logs if applicable**
You can set your [config](https://github.com/philosowaffle/peloton-to-garmin/blob/master/configuration.example.json#L50) to `"Debug"` to get more detailed logs.
```
$ docker-compose up
Traceback (most recent call last):
  File "urllib3/connectionpool.py", line 670, in urlopen
  File "urllib3/connectionpool.py", line 392, in _make_request
  File "http/client.py", line 1255, in request
  File "http/client.py", line 1301, in _send_request
  File "http/client.py", line 1250, in endheaders
  File "http/client.py", line 1010, in _send_output
  File "http/client.py", line 950, in send
  File "docker/transport/unixconn.py", line 43, in connect
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests/adapters.py", line 439, in send
  File "urllib3/connectionpool.py", line 726, in urlopen
  File "urllib3/util/retry.py", line 410, in increment
  File "urllib3/packages/six.py", line 734, in reraise
  File "urllib3/connectionpool.py", line 670, in urlopen
  File "urllib3/connectionpool.py", line 392, in _make_request
  File "http/client.py", line 1255, in request
  File "http/client.py", line 1301, in _send_request
  File "http/client.py", line 1250, in endheaders
  File "http/client.py", line 1010, in _send_output
  File "http/client.py", line 950, in send
  File "docker/transport/unixconn.py", line 43, in connect
urllib3.exceptions.ProtocolError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker/api/client.py", line 214, in _retrieve_server_version
  File "docker/api/daemon.py", line 181, in version
  File "docker/utils/decorators.py", line 46, in inner
  File "docker/api/client.py", line 237, in _get
  File "requests/sessions.py", line 543, in get
  File "requests/sessions.py", line 530, in request
  File "requests/sessions.py", line 643, in send
  File "requests/adapters.py", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 81, in main
  File "compose/cli/main.py", line 200, in perform_command
  File "compose/cli/command.py", line 60, in project_from_options
  File "compose/cli/command.py", line 152, in get_project
  File "compose/cli/docker_client.py", line 41, in get_client
  File "compose/cli/docker_client.py", line 170, in docker_client
  File "docker/api/client.py", line 197, in __init__
  File "docker/api/client.py", line 221, in _retrieve_server_version
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
[92172] Failed to execute script docker-compose
```

**Installation (please complete the following information):**
 - OS: MacOS
 - Method: docker
 - Version: MacOS 12.1, Docker Desktop 4.1.1

**Additional context**

**Comment by philosowaffle** [comment]
```
  File "docker/transport/unixconn.py", line 43, in connect
FileNotFoundError: [Errno 2] No such file or directory
....
....
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
[92172] Failed to execute script docker-compose
```

These errors are coming from docker and/or docker-compose, not P2G. This seems like an issue with either your docker or docker-compose installation. 

As a quick sanity check, each of these commands should run successfully and print out version information for each respective tool.
```
> docker -v
> docker-compose -v
```

Assuming docker/docker-compose are installed and working correctly, the only steps are to create the `configuration.local.json` file and run `docker-compose up`.

**Comment by philosowaffle** [comment]
An example of what error messages will look like from P2G, below is a container I spun up just now using the [example docker-compose.yaml](https://github.com/philosowaffle/peloton-to-garmin/blob/master/docker-compose.yaml) file and the [example configuration.local.json](https://github.com/philosowaffle/peloton-to-garmin/blob/master/configuration.example.json) from the P2G documentation.  We can see in the output it failed to authenticate with Peloton, this is expected because I copy/pasted the example configuration file and did not update it with my Peloton credentials. This is how you can expect the examples to behave even without any modification.

```sh
$ ls
configuration.local.json  docker-compose.yaml

$ docker-compose up
Starting p2g-console ... done
Attaching to p2g-console
p2g-console    | Peloton To Garmin
p2g-console    | [13:57:43 ERR] Http Call Failed. Unauthorized {"status":401,"error_code":3010,"subcode":null,"message":"Login failed","details":null}
p2g-console    | [13:57:43 FTL] Failed to authenticate with Peloton.
p2g-console    | Flurl.Http.FlurlHttpException: Call failed with status code 401 (Unauthorized): POST https://api.onepeloton.com/auth/login
p2g-console    |    at Flurl.Http.FlurlRequest.HandleExceptionAsync(FlurlCall call, Exception ex, CancellationToken token)
p2g-console    |    at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption)
p2g-console    |    at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption)
p2g-console    |    at Flurl.Http.ResponseExtensions.ReceiveJson[T](Task`1 response)
p2g-console    |    at Peloton.ApiClient.InitAuthAsync(String overrideUserAgent) in /build/src/Peloton/ApiClient.cs:line 54
p2g-console    | [13:57:43 INF] No download directory found. Nothing to do. ./working/downloaded
p2g-console    | [13:57:43 INF] Done.
p2g-console exited with code 0
```

**Comment by law** [comment]
Well shucks, I feel exceptionally silly.  Apparently my docker daemon wasn't running.  If I run `docker-compose up`, it gives me the cryptic message above.  If I run 'docker compose up' (note the lack of a dash) it gives me a very plain "Hey, Is the docker daemon running?" error.  Problem solved, root cause: PEBKAC.  Thanks so much for the quick reply!

**Comment by philosowaffle** [comment]
No need to feel silly, that was an exceptionally cryptic error message.  I'm glad you figured it out :)
