### ISSUE TITLE
Multiple Issues with Github Actions. 

### ISSUE THREAD

**Issue by BharaniManav** [philosowaffle/peloton-to-garmin#258]
**Describe the bug**
After following all the instructions I was able to successfully upload the peloton workouts into garmin connect. There are few issues that I face,
1. Error in the run sync. 
Welcome! P2G is starting up...
[05:09:17 ERR] Failed to get syncServiceStatus from db
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at JsonFlatFileDataStore.DataStore.GetItem[T](String key)
   at Common.Database.SyncStatusDb.GetSyncStatusAsync() in /build/src/Common/Database/SyncStatusDb.cs:line 38
   
2. Timezone in the workouts uploaded shows azores time zone and all the workouts are in future so I did my workout at 7pm PST is posted for tomorrow. 
3. If sync workflow runs more than once it duplicates in garmin connect. This is not duplicate with the workout recorded in Garmin but multiple entries from peloton. 

**To Reproduce**

**Expected behavior**

**Logs**
```
Paste Log output here
```

**Installation (please complete the following information):**
 - Github Actions
 - Fork'ed Latest as of yesterday.

**Additional context**

**Comment by philosowaffle** [comment]
1. This is a benign error message and can be ignored

2. @dkuwahara Is there a solution for this?

3. Can you clarify more on what is happening, perhaps provide an example?

**Comment by dkuwahara** [comment]
The action is using the `stable` tag from this repo. Any time zone bug would likely exist within all other methods of syncing. From what I can tell... it's taking the local time of the ride but treating it as UTC. So if I take a ride at 1:47PM MDT the sync will take that as 7:47PM UTC and then submit it as a 7:47PM ride.

**Comment by dkuwahara** [comment]
Interestingly, it looks like the if you download the FIT file off Garmin it does have to correct time in the file.

**Comment by philosowaffle** [comment]
@dkuwahara When running a docker container, the container can be supplied a TimeZone environment variable that will ensure the process uses the correct TimeZone. This is how P2G knows what timezone to use when doing conversions.
 
Example: https://github.com/philosowaffle/peloton-to-garmin/blob/master/docker/docker-compose.yaml#L8

**Comment by BharaniManav** [comment]
@philosowaffle for your last comment. I’m running this from GitHub actions workflow. It works like a charm other than the timezone issue. @dkuwahara is there a parameter that needs to be set for timezone. 

Follow-up to your comment on issue no. 3 above. I ran multiple time and hole I was setting up. The two runs when it started to work actually created two entries for the same workout except the device info part.

**Comment by philosowaffle** [comment]
Regarding the duplicate upload to Garmin, lets first fix the missing TimeZone parameter and see if that also addresses this issue.

Typically (I tested this again just now), Garmin rejects duplicate uploads and it does this by using things like the workouts timestamp to identify if the workout already exists.  Its possible that when the workout has a date set in the future, the logic on Garmin's end is failing and they are allowing the duplicate through.

**Comment by BharaniManav** [comment]
Agreed…!! Let me know if you need me to try something….

**Comment by dkuwahara** [comment]
You would be better off setting the timezone yourself in the action file as there's no single timezone that will suit everyone.

**Comment by BharaniManav** [comment]
Thanks. Could you please point me to the right file. I can give it a shot and report back..

**Comment by dkuwahara** [comment]
https://github.com/philosowaffle/peloton-to-garmin/blob/master/.github/workflows/sync_peloton_to_garmin.yml

You would add the environment variable to the last line of the YAML in this case

**Comment by dkuwahara** [comment]
Duplicates will happen if you do something like change the device info and rerun the action on the same set of rides. If you pass in the same inputs it will properly dedupe the rides.

**Comment by BharaniManav** [comment]
Added link below and it worked great.
![image](https://user-images.githubusercontent.com/105683221/168960974-85e60cea-e835-447a-88dc-8668449d3d6a.png)

Few outstanding question I have is(May be i've to read docs more).. 
1) I've 2 workouts now, one from peloton and one from Garmin kind of duplicate. 
2) Peloton impact area is blank whereas my garmin shows some impacted areas. Refer below 
Garmin:
![image](https://user-images.githubusercontent.com/105683221/168961259-24b4f1c5-e257-428c-9014-e31aa8fa0868.png)
Peloton: 
![image](https://user-images.githubusercontent.com/105683221/168961298-3618bcc5-2059-4b1a-9966-459f5f1cf822.png)

**Comment by philosowaffle** [comment]
In the case of recording an activity on your watch and syncing the workout from Peloton, duplicates are expected. In this case, the two workout files are different enough that neither Garmin, nor P2G will be able to identify that this is the same workout.  Generally, when using P2G, its recommended to Discard the watch workout at the end instead of clicking Save.  See the [Typical Usage](https://philosowaffle.github.io/peloton-to-garmin/features.html#typical-usage) documentation.

Regarding Muscle Groups, your Garmin watch is likely guessing, based on what motions it detected. For a Strength workout synced from Peloton this information will not be available.  If you prefer the data your watch captured over the synced Peloton data, then you can configured P2G to [exclude Strength workouts](https://philosowaffle.github.io/peloton-to-garmin/configuration/json.html#peloton-config). This will stop P2G from syncing those workouts.
