### ISSUE TITLE
[Bug] Trying to back-sync lots of workouts: [ERR] Http Call Failed. null 

### ISSUE THREAD

**Issue by philosowaffle** [philosowaffle/peloton-to-garmin#343]
Issues:
1. Why are we printing `Http Call Failed. null` without any other useful information?
2. Can catch SSL exception and log more meaningful error message?
3. Batch workouts and only sync a batch of X at a time will hopefully resolve this

**Describe the bug**
When trying to back-sync lots of workouts (hundreds?) users are hitting below error.  I think this is a result of switching to async data loading. We may be flooding Peloton with requests and getting rejected.

**To Reproduce**
1. Try to backfill hundreds of workouts

**Logs**
```
2022-09-25 11:08:39.274 -05:00 [INF] App Version: 3.0.3
2022-09-25 11:08:39.334 -05:00 [INF] Operating System: Microsoft Windows NT 10.0.19043.0
2022-09-25 11:08:39.336 -05:00 [INF] DotNet Runtime: 6.0.8
....
2022-09-25 11:08:50.659 -05:00 [ERR] Http Call Failed. null 
2022-09-25 11:08:50.662 -05:00 [ERR] Http Call Failed. null 
2022-09-25 11:08:50.667 -05:00 [ERR] Http Call Failed. null 
2022-09-25 11:08:50.670 -05:00 [ERR] Http Call Failed. null 
2022-09-25 11:08:50.672 -05:00 [ERR] Http Call Failed. null 
2022-09-25 11:08:50.675 -05:00 [ERR] Http Call Failed. null 
2022-09-25 11:08:50.677 -05:00 [ERR] Http Call Failed. null 
2022-09-25 11:08:50.682 -05:00 [ERR] Http Call Failed. null 
2022-09-25 11:08:50.685 -05:00 [ERR] Http Call Failed. null 
2022-09-25 11:08:50.687 -05:00 [ERR] Http Call Failed. null 
2022-09-25 11:08:50.689 -05:00 [ERR] Http Call Failed. null 
2022-09-25 11:08:50.691 -05:00 [ERR] Http Call Failed. null 
2022-09-25 11:08:50.694 -05:00 [ERR] Http Call Failed. null 
2022-09-25 11:08:50.700 -05:00 [ERR] Http Call Failed. null 
2022-09-25 11:08:50.702 -05:00 [ERR] Http Call Failed. null 
2022-09-25 11:08:50.704 -05:00 [ERR] Http Call Failed. null 
2022-09-25 11:08:50.707 -05:00 [ERR] Http Call Failed. null 
2022-09-25 11:08:50.710 -05:00 [ERR] Http Call Failed. null 
2022-09-25 11:08:50.715 -05:00 [ERR] Http Call Failed. null 
2022-09-25 11:08:50.718 -05:00 [ERR] Http Call Failed. null 
2022-09-25 11:08:50.720 -05:00 [ERR] Http Call Failed. null 
2022-09-25 11:08:50.722 -05:00 [ERR] Http Call Failed. null 
2022-09-25 11:08:50.728 -05:00 [ERR] Http Call Failed. null 
2022-09-25 11:08:50.731 -05:00 [ERR] Http Call Failed. null 
2022-09-25 11:08:50.733 -05:00 [ERR] Http Call Failed. null 
2022-09-25 11:08:50.735 -05:00 [ERR] Http Call Failed. null 
2022-09-25 11:08:50.737 -05:00 [ERR] Http Call Failed. null 
2022-09-25 11:08:50.740 -05:00 [ERR] Http Call Failed. null 
2022-09-25 11:08:50.745 -05:00 [ERR] Http Call Failed. null 
2022-09-25 11:08:50.747 -05:00 [ERR] Http Call Failed. null 
2022-09-25 11:08:50.750 -05:00 [ERR] Http Call Failed. null 
2022-09-25 11:08:50.751 -05:00 [ERR] Http Call Failed. null 
2022-09-25 11:08:50.755 -05:00 [ERR] Http Call Failed. null 
2022-09-25 11:08:50.759 -05:00 [ERR] Http Call Failed. null 
2022-09-25 11:08:50.761 -05:00 [ERR] Http Call Failed. null 
2022-09-25 11:08:56.814 -05:00 [ERR] Failed to download workouts from Peloton.
Flurl.Http.FlurlHttpException: Call failed. The SSL connection could not be established, see inner exception: GET https://api.onepeloton.com/api/workout/7d9a03d4a0854db4a03778a4cfff80ef/performance_graph?every_n=1
 ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.IO.IOException: Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host..
 ---> System.Net.Sockets.SocketException (10054): An existing connection was forcibly closed by the remote host.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.CreateException(SocketError error, Boolean forAsyncThrow)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.SendAsyncForNetworkStream(Socket socket, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.SendAsyncForNetworkStream(ReadOnlyMemory`1 buffer, SocketFlags socketFlags, CancellationToken cancellationToken)
   at System.Net.Sockets.NetworkStream.WriteAsync(ReadOnlyMemory`1 buffer, CancellationToken cancellationToken)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Security.SslStream.ProcessAuthenticationAsync(Boolean isAsync, Boolean isApm, CancellationToken cancellationToken)
   at System.Net.Security.SslStream.AuthenticateAsClientAsync(SslClientAuthenticationOptions sslClientAuthenticationOptions, CancellationToken cancellationToken)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1.SetResult(TResult result)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(Task`1 task, TResult result)
   at System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder.SetResult()
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.InvokeContinuation(Action`1 continuation, Object state, Boolean forceAsync, Boolean requiresExecutionContextFlow)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.OnCompleted(SocketAsyncEventArgs _)
   at System.Net.Sockets.SocketAsyncEventArgs.<DnsConnectAsync>g__Core|112_0(MultiConnectSocketAsyncEventArgs internalArgs, Task`1 addressesTask, Int32 port, SocketType socketType, ProtocolType protocolType, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
   at System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore`1.SignalCompletion()
   at System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore`1.SetResult(TResult result)
   at System.Net.Sockets.SocketAsyncEventArgs.MultiConnectSocketAsyncEventArgs.OnCompleted(SocketAsyncEventArgs e)
   at System.Net.Sockets.SocketAsyncEventArgs.ExecutionCallback(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pNativeOverlapped)
--- End of stack trace from previous location ---

   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   --- End of inner exception stack trace ---
   at Flurl.Http.FlurlRequest.HandleExceptionAsync(FlurlCall call, Exception ex, CancellationToken token)
   at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Flurl.Http.ResponseExtensions.ReceiveJson[T](Task`1 response)
   at Peloton.PelotonService.GetWorkoutDetailsAsync(String workoutId) in D:\a\peloton-to-garmin\peloton-to-garmin\src\Peloton\PelotonService.cs:line 141
   at Peloton.PelotonService.GetWorkoutDetailsAsync(ICollection`1 workoutIds) in D:\a\peloton-to-garmin\peloton-to-garmin\src\Peloton\PelotonService.cs:line 128
   at Sync.SyncService.SyncAsync(ICollection`1 workoutIds, ICollection`1 exclude) in D:\a\peloton-to-garmin\peloton-to-garmin\src\Sync\SyncService.cs:line 158
```

**Installation (please complete the following information):**
 - OS: [\windows]
 - Method: [exe]
 - Version: [3.0.3]

**Additional context**
#341

**Comment by philosowaffle** [comment]
> When trying to back-sync lots of workouts (hundreds?) users are hitting below error. I think this is a result of switching to async data loading. We may be flooding Peloton with requests and getting rejected.

Tested this theory out locally and was not able to reproduce the problem. Syncing ~500 workouts asynchronously worked fine.

**Comment by philosowaffle** [comment]
Ultimately, still believe this a host resource exhaustion problem and would specific to how many resources the host machine has available.

Solution:
1. When fetching workouts in parallel from Peloton, do batches of 25 at a time
2. Add Polly retry policy for cases when we might timeout with Peloton
