### ISSUE TITLE
Failure to convert workout. KeyNotFoundException

### ISSUE THREAD

**Issue by adepue** [philosowaffle/peloton-to-garmin#354]
**Describe the bug**
[16:36:25 INF] Converting workouts...
[16:36:[25](https://github.com/adepue/peloton-to-garmin/actions/runs/3291356401/jobs/5425402381#step:6:26) ERR] Failed to save default Settings to Db.
[16:36:25 ERR] Failed to convert workout data to format Fit 720b11e3224c405188e42ab2016712[26](https://github.com/adepue/peloton-to-garmin/actions/runs/3291356401/jobs/5425402381#step:6:27)_5_min_Post-Ride_Stretch_with_Denis_Morton
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at JsonFlatFileDataStore.DataStore.GetItem[T](String key)
   at Common.Database.SettingsDb.GetSettingsAsync() in /build/src/Common/Database/SettingsDb.cs:line 39
   at Common.Database.SettingsDb.GetSettingsAsync() in /build/src/Common/Database/SettingsDb.cs:line 49
   at Common.Service.SettingsService.GetSettingsAsync() in /build/src/Common/Service/SettingsService.cs:line 38
   at Common.Service.SettingsService.GetCustomDeviceInfoAsync(String garminEmail) in /build/src/Common/Service/SettingsService.cs:line 145
   at Conversion.Converter`1.GetDeviceInfoAsync(FitnessDiscipline sport, Settings settings) in /build/src/Conversion/IConverter.cs:line 481
   at Conversion.FitConverter.ConvertAsync(Workout workout, WorkoutSamples workoutSamples, UserData userData, Settings settings) in /build/src/Conversion/FitConverter.cs:line 77
   at Conversion.Converter`1.ConvertForFormatAsync(FileFormat format, P2GWorkout workoutData, Settings settings) in /build/src/Conversion/IConverter.cs:line 97

**To Reproduce**
1. Launch sync workflow via github actions.
2. See "success" on job, but failure in logs.

**Expected behavior**

**Logs**
[16:36:25 INF] Converting workouts...
[16:36:[25](https://github.com/adepue/peloton-to-garmin/actions/runs/3291356401/jobs/5425402381#step:6:26) ERR] Failed to save default Settings to Db.
[16:36:25 ERR] Failed to convert workout data to format Fit 720b11e3224c405188e42ab2016712[26](https://github.com/adepue/peloton-to-garmin/actions/runs/3291356401/jobs/5425402381#step:6:27)_5_min_Post-Ride_Stretch_with_Denis_Morton
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at JsonFlatFileDataStore.DataStore.GetItem[T](String key)
   at Common.Database.SettingsDb.GetSettingsAsync() in /build/src/Common/Database/SettingsDb.cs:line 39
   at Common.Database.SettingsDb.GetSettingsAsync() in /build/src/Common/Database/SettingsDb.cs:line 49
   at Common.Service.SettingsService.GetSettingsAsync() in /build/src/Common/Service/SettingsService.cs:line 38
   at Common.Service.SettingsService.GetCustomDeviceInfoAsync(String garminEmail) in /build/src/Common/Service/SettingsService.cs:line 145
   at Conversion.Converter`1.GetDeviceInfoAsync(FitnessDiscipline sport, Settings settings) in /build/src/Conversion/IConverter.cs:line 481
   at Conversion.FitConverter.ConvertAsync(Workout workout, WorkoutSamples workoutSamples, UserData userData, Settings settings) in /build/src/Conversion/FitConverter.cs:line 77
   at Conversion.Converter`1.ConvertForFormatAsync(FileFormat format, P2GWorkout workoutData, Settings settings) in /build/src/Conversion/IConverter.cs:line 97

**Installation (please complete the following information):**
 - OS: [mac, linux, windows]. GH Actions sync workflow
 - Method: [source, exe, docker]. 
 - Version: [1.2.0, 2.0.1, dockerTag, etc] - master tag

**Additional context**

**Comment by adepue** [comment]
@philosowaffle  after syncing my fork to yours and running the Action again, the problem persists... Any more information I can share?

**Comment by philosowaffle** [comment]
Try one more time. The Action is pinned to the docker `stable` tag which took a bit to build and just got pushed a few minutes ago.

**Comment by adepue** [comment]
Worked great.  Thank you!!
