### ISSUE TITLE
parsing of peloton data error

### ISSUE THREAD

**Issue by hotbread613** [philosowaffle/peloton-to-garmin#373]
### ERROR REPORT 1
Had been running 3.1.1 without any errors through Terminal on Macbook Pro 13.0.1. Then, the install stopped working and I got the following errors.

[12:04:20 ERR] Failed to fetch recent workouts from Peleoton.
Flurl.Http.FlurlParsingException: Response could not be deserialized to JSON: GET https://api.onepeloton.com/api/user/079030315eb0431b8bdb4cb60392b06d/workouts?limit=1&sort_by=-created&page=0&joins=ride
 ---> Newtonsoft.Json.JsonSerializationException: Error converting value "caesar" to type 'Common.Dto.Peloton.FitnessDiscipline'. Path 'data[0].fitness_discipline', line 1, position 116.
 ---> System.ArgumentException: Requested value 'caesar' was not found.
   at Newtonsoft.Json.Utilities.EnumUtils.ParseEnum(Type enumType, NamingStrategy namingStrategy, String value, Boolean disallowNumber)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)
   at Flurl.Http.Configuration.NewtonsoftJsonSerializer.Deserialize[T](Stream stream)
   at Flurl.Http.FlurlResponse.GetJsonAsync[T]()
   --- End of inner exception stack trace ---
   at Flurl.Http.FlurlRequest.HandleExceptionAsync(FlurlCall call, Exception ex, CancellationToken token)
   at Flurl.Http.FlurlResponse.GetJsonAsync[T]()
   at Flurl.Http.ResponseExtensions.ReceiveJson[T](Task`1 response)
   at Peloton.ApiClient.GetWorkoutsAsync(Int32 pageSize, Int32 page) in /Applications/p2garmin/src/Peloton/ApiClient.cs:line 87
   at Peloton.PelotonService.GetRecentWorkoutsAsync(Int32 numWorkoutsToDownload) in /Applications/p2garmin/src/Peloton/PelotonService.cs:line 116
   at Sync.SyncService.SyncAsync(Int32 numWorkouts) in /Applications/p2garmin/src/Sync/SyncService.cs:line 81

### ERROR REPORT 2
Installed WebUI version 3.1.1 to see if it would work there. Running on Macbook Pro OS 13.0.1 in Chrome Version 108.0.5359.94. Installed Using Docker. Getting the following Error: 

> Failed to load Peloton workouts - Call failed with status code 500 (Internal Server Error): GET http://p2g-api:8080/api/peloton/workouts?PageSize=25&PageIndex=0

**Comment by hotbread613** [comment]
I just got it yesterday. So perhaps it's related. I'll install the update you referenced in the post and follow up inn that thread-David HoreshOn Dec 5, 2022, at 13:28, Bailey ***@***.***> wrote:﻿
Do you have a Rower? think this is a duplicate of #370
