### ISSUE TITLE
Failed to download workouts from Peloton

### ISSUE THREAD

**Issue by neildsb** [philosowaffle/peloton-to-garmin#463]
App works fine with my wife's profile, 

2023-04-05 07:17:09.221 +01:00 [INF] *********************************************
2023-04-05 07:17:09.267 +01:00 [INF] P2G Version: p2g_console 3.5.0-rc
2023-04-05 07:17:09.273 +01:00 [INF] Operating System: Win32NT
2023-04-05 07:17:09.274 +01:00 [INF] OS Version: Microsoft Windows NT 10.0.22621.0
2023-04-05 07:17:09.276 +01:00 [INF] DotNet Runtime: Microsoft Windows NT 10.0.22621.0
2023-04-05 07:17:09.277 +01:00 [INF] Docker Deployment: false
2023-04-05 07:17:09.281 +01:00 [INF] Config path: C:\Users\Neil\Documents\P2G-Neil\win10-x64_142-4558649288\configuration.local.json
2023-04-05 07:17:09.282 +01:00 [INF] *********************************************
2023-04-05 07:17:11.237 +01:00 [INF] *********************************************
2023-04-05 07:17:11.253 +01:00 [INF] *********************************************
2023-04-05 07:17:12.291 +01:00 [INF] Found 6 completed workouts.
2023-04-05 07:17:14.561 +01:00 [ERR] Failed to download workouts from Peloton.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Common.Dto.Extensions.GetClassPlanExercises(Workout workout, RideSegments rideSegments) in D:\a\peloton-to-garmin\peloton-to-garmin\src\Common\Dto\P2GWorkout.cs:line 59
   at Peloton.PelotonService.GetWorkoutDetailsAsync(String workoutId) in D:\a\peloton-to-garmin\peloton-to-garmin\src\Peloton\PelotonService.cs:line 283
   at Peloton.PelotonService.GetWorkoutDetailsAsync(ICollection`1 workoutIds) in D:\a\peloton-to-garmin\peloton-to-garmin\src\Peloton\PelotonService.cs:line 253
   at Sync.SyncService.SyncAsync(IEnumerable`1 workoutIds, ICollection`1 exclude) in D:\a\peloton-to-garmin\peloton-to-garmin\src\Sync\SyncService.cs:line 81
2023-04-05 07:17:14.897 +01:00 [INF] Done
2023-04-05 07:17:14.900 +01:00 [INF] Sleeping for 86400 seconds...

![image](https://user-images.githubusercontent.com/91122872/229999011-273db255-0451-4a2a-b241-66b66342acbf.png)

**Comment by neildsb** [comment]
** update **

it only is a problem with the 'Strength' classes, if I set the DL to '1' I can pull the 'Stretch' class ok

**Comment by neildsb** [comment]
** update 2 **

tried P2G Version: p2g_console 3.4.1,

found the following errors and mapping

2023-04-05 08:38:33.732 +01:00 [INF] Found 3 completed workouts.
2023-04-05 08:38:35.155 +01:00 [INF] Found 3 workouts remaining after filtering ExcludedWorkoutTypes.
2023-04-05 08:38:35.158 +01:00 [INF] Converting workouts...
2023-04-05 08:38:35.328 +01:00 [ERR] Found Peloton Strength exercise with no Garmin mapping: Reverse Fly 3df6a1136a7a4e4db31e104c7d5a0fcf
2023-04-05 08:38:35.330 +01:00 [ERR] Found Peloton Strength exercise with no Garmin mapping: Reverse Fly 3df6a1136a7a4e4db31e104c7d5a0fcf
2023-04-05 08:38:35.331 +01:00 [ERR] Found Peloton Strength exercise with no Garmin mapping: Reverse Fly 3df6a1136a7a4e4db31e104c7d5a0fcf
2023-04-05 08:38:35.333 +01:00 [ERR] Found Peloton Strength exercise with no Garmin mapping: Renegade Row ed9adea36e77459dab7c189884ceb7ab
2023-04-05 08:38:35.334 +01:00 [ERR] Found Peloton Strength exercise with no Garmin mapping: Renegade Row ed9adea36e77459dab7c189884ceb7ab
2023-04-05 08:38:35.336 +01:00 [ERR] Found Peloton Strength exercise with no Garmin mapping: Renegade Row ed9adea36e77459dab7c189884ceb7ab
2023-04-05 08:38:35.339 +01:00 [ERR] Found Peloton Strength exercise with no Garmin mapping: Renegade Row ed9adea36e77459dab7c189884ceb7ab
2023-04-05 08:38:35.340 +01:00 [ERR] Found Peloton Strength exercise with no Garmin mapping: Renegade Row ed9adea36e77459dab7c189884ceb7ab
2023-04-05 08:38:35.341 +01:00 [ERR] Found Peloton Strength exercise with no Garmin mapping: Renegade Row ed9adea36e77459dab7c189884ceb7ab
2023-04-05 08:38:35.431 +01:00 [INF] [@Format] Backed up file "Fit"
2023-04-05 08:38:35.453 +01:00 [ERR] Found Peloton Strength exercise with no Garmin mapping: Reverse Fly 3df6a1136a7a4e4db31e104c7d5a0fcf
2023-04-05 08:38:35.457 +01:00 [ERR] Found Peloton Strength exercise with no Garmin mapping: Reverse Fly 3df6a1136a7a4e4db31e104c7d5a0fcf
2023-04-05 08:38:35.459 +01:00 [ERR] Found Peloton Strength exercise with no Garmin mapping: Front Raise a9cefac3b8234bc0bc0ee8deb62d67d3
2023-04-05 08:38:35.460 +01:00 [ERR] Found Peloton Strength exercise with no Garmin mapping: Lateral Raise 2635cbe093a140e0be83be83fa594d8b
2023-04-05 08:38:35.466 +01:00 [ERR] Found Peloton Strength exercise with no Garmin mapping: Front Raise a9cefac3b8234bc0bc0ee8deb62d67d3
2023-04-05 08:38:35.468 +01:00 [ERR] Found Peloton Strength exercise with no Garmin mapping: Lateral Raise 2635cbe093a140e0be83be83fa594d8b
2023-04-05 08:38:35.470 +01:00 [ERR] Found Peloton Strength exercise with no Garmin mapping: Cross Body Curl a66b797fc2014b799cc0cb114d9c5079
2023-04-05 08:38:35.472 +01:00 [ERR] Found Peloton Strength exercise with no Garmin mapping: Standing Chest Fly 021047bf0cff470bb2d11f94d3539cfe
2023-04-05 08:38:35.475 +01:00 [ERR] Found Peloton Strength exercise with no Garmin mapping: Cross Body Curl a66b797fc2014b799cc0cb114d9c5079
2023-04-05 08:38:35.478 +01:00 [ERR] Found Peloton Strength exercise with no Garmin mapping: Standing Chest Fly 021047bf0cff470bb2d11f94d3539cfe

**Comment by philosowaffle** [comment]
@neildsb can you give this version version a try? think it will address the error.

https://github.com/philosowaffle/peloton-to-garmin/suites/12094845929/artifacts/636922537

**Comment by neildsb** [comment]
looks good, found another mapping for you :-)

[18:48:25 INF] Operating System: Win32NT
[18:48:25 INF] OS Version: Microsoft Windows NT 10.0.22621.0
[18:48:25 INF] DotNet Runtime: Microsoft Windows NT 10.0.22621.0
[18:48:25 INF] Docker Deployment: False
[18:48:25 INF] Config path: C:\Users\cookn\OneDrive\Documents\Peloton-to-garmin\win10-x64_144-4638820724\configuration.local.json
[18:48:25 INF] *********************************************
[18:48:25 INF] *********************************************
[18:48:25 INF] *********************************************
[18:48:26 INF] Found 3 completed workouts.
[18:48:28 INF] Found 3 workouts remaining after filtering ExcludedWorkoutTypes.
[18:48:28 INF] Converting workouts...
[18:48:28 INF] Found Peloton Strength exercise with no Garmin mapping: **Wide Grip Chest Press** 94e3c37e0cb245f78e195b115a400112

**Comment by philosowaffle** [comment]
The fix and the Wide Grip Chest Press changes are now published in the latest release 3.5.0 

https://github.com/philosowaffle/peloton-to-garmin/releases
