### ISSUE TITLE
Authentication error

### ISSUE THREAD

**Issue by Ficklejam** [philosowaffle/peloton-to-garmin#544]
**Describe the bug**
Auth error

**To Reproduce**
1. Run program
2. errors with authentication
3. workouts to upload don't upload

**Expected behavior**
Expected to upload peloton ride to Garmin

**Logs**
```
[21:38:33 INF] *********************************************
[21:38:33 INF] P2G Version: p2g_console 3.5.1
[21:38:33 INF] Operating System: Win32NT
[21:38:33 INF] OS Version: Microsoft Windows NT 10.0.22000.0
[21:38:33 INF] DotNet Runtime: Microsoft Windows NT 10.0.22000.0
[21:38:33 INF] Docker Deployment: False
[21:38:33 INF] Config path: C:\Users\Gallium\Documents\P2Gv3.5.1\configuration.local.json
[21:38:33 INF] *********************************************
[21:38:33 INF] Application started. Press Ctrl+C to shut down.
[21:38:33 INF] Hosting environment: Production
[21:38:33 INF] Content root path: C:\Users\Gallium\Documents\P2Gv3.5.1
[21:38:34 INF] *********************************************
[21:38:34 INF] *********************************************
[21:38:34 INF] Found 20 completed workouts.
[21:38:37 INF] Found 9 workouts remaining after filtering ExcludedWorkoutTypes.
[21:38:37 INF] Converting workouts...
[21:38:37 INF] [@Format] Backed up file Fit
[21:38:37 INF] [@Format] Backed up file Fit
[21:38:37 INF] [@Format] Backed up file Fit
[21:38:37 INF] [@Format] Backed up file Fit
[21:38:37 INF] [@Format] Backed up file Fit
[21:38:37 INF] [@Format] Backed up file Fit
[21:38:37 INF] [@Format] Backed up file Fit
[21:38:37 INF] [@Format] Backed up file Fit
[21:38:37 INF] [@Format] Backed up file Fit
[21:38:37 INF] Uploading workouts to Garmin...
[21:38:39 INF] HTTP Request: GET - https://connect.garmin.com/modern/ - Cookie: __cflb=02DiuJLbVZHipNWxN8yYRX3u8XkAfEE59hivU9zWCH1Zv; _cfuvid=4S_CiCn5IsaBvboWDCAmX4BFie8YyuXxz_ATttStuIM-1696477118926-0-604800000; ADRUM_BTa=R:0|g:149b6143-8bb4-4b6c-bccb-03ed4169909b|n:garmin_869629ee-d273-481d-b5a4-f4b0a8c4d5a3; SameSite=None; SESSIONID=YmUzMWU1ZmUtOWJkNS00Yjg1LWFiYWYtZDFjNjk4NmFlMThk
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:48.0) Gecko/20100101 Firefox/50.0
Accept-Encoding: gzip, deflate
 -
[21:38:39 INF] HTTP Response: Redirect - GET - https://connect.garmin.com/modern/ - Date: Thu, 05 Oct 2023 03:38:39 GMT
Connection: keep-alive
Cache-Control: no-store, must-revalidate, no-cache, max-age=0
Location: https://connect.garmin.com/signin/?service=https%3A%2F%2Fconnect.garmin.com%2Fmodern%2F
Pragma: no-cache
Set-Cookie: ADRUM_BTa=R:0|g:149b6143-8bb4-4b6c-bccb-03ed4169909b|n:garmin_869629ee-d273-481d-b5a4-f4b0a8c4d5a3; Max-Age=0; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Path=/; Secure, ADRUM_BTa=R:0|g:da4af86f-aa8a-47d3-a93e-f6e5c5700d82; Max-Age=30; Expires=Thu, 05-Oct-2023 03:39:09 GMT; Path=/; Secure, ADRUM_BTa=R:0|g:da4af86f-aa8a-47d3-a93e-f6e5c5700d82|n:garmin_869629ee-d273-481d-b5a4-f4b0a8c4d5a3; Max-Age=30; Expires=Thu, 05-Oct-2023 03:39:09 GMT; Path=/; Secure, SameSite=None; Max-Age=30; Expires=Thu, 05-Oct-2023 03:39:09 GMT; Path=/; Secure, SESSIONID=; Max-Age=0; Expires=Thu, 1 Jan 1970 00:00:00 GMT; Path=/; Secure; HttpOnly; SameSite=Lax
Strict-Transport-Security: max-age=31536000 ; includeSubDomains
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
x-vcap-request-id: 0953d75b-20ae-4566-4a4d-1f71d95292c3
X-XSS-Protection: 1; mode=block
CF-Cache-Status: DYNAMIC
Report-To: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=E%2BRs9lzNQAZ9eEllyLNt8XppAn%2Fc1Gg1QvaS3k%2BNzuS3KuN6ZAO%2BcIJXEy7bbMA3LrCa7SLwg7TxmviaqDrSW1prAYg0QYUHqAJ4gtISFHpjRx1tcoAH%2BIRxfktsZDYD3MFDNw%3D%3D"}],"group":"cf-nel","max_age":604800}
NEL: {"success_fraction":0.01,"report_to":"cf-nel","max_age":604800}
Server: cloudflare
CF-RAY: 8112a20b3aa05198-DEN
 -
[21:38:39 INF] HTTP Request: GET - https://sso.garmin.com/sso/login?service=https%3A%2F%2Fconnect.garmin.com%2Fmodern%2F&webhost=https%3A%2F%2Fconnect.garmin.com&gateway=true&generateExtraServiceTicket=true&generateTwoExtraServiceTickets=true&clientId=GarminConnect - Cookie: SESSION=3ad0918f-89fa-47f2-a49e-e37957e8b05c; __VCAP_ID__=0f988968-548d-4b49-5b81-9cdf; __cflb=02DiuDJkcGSAXY7wCCWx43Xfs6shTRQ6M1H1St7Ng5JLc; __cf_bm=B4TJOPdwbBdESPr0GUN.Sbpckqa7kPTHkKhTNidaV28-1696477117-0-AWl/9I1GpOBW2umupVVsspNUBanB7RS+byz+zwuYZizaUqiKTE6HsMS4pTRnt3l0yOwTiDm/tSqJtoX3t7Tl0Ik=; _cfuvid=3vqlRP3VovRg2N2CzY93HkXMEDIHP94mFkybvPAIRhA-1696477117745-0-604800000; org.springframework.web.servlet.i18n.CookieLocaleResolver.LOCALE=en_US; GARMIN-SSO=1; GarminNoCache=true; GARMIN-SSO-GUID=D260B038F4EFBDA960F51D11BCD1332CB15F2C7B; GARMIN-SSO-CUST-GUID=6338fc67-366e-454e-a6df-0adb72e660a0; CASTGC=TGT-66074-zlF6jzwRsHCnnDrNmX1BUPSX2xBf4iCngqvOedVTHl6gkaEphv-cas; __cfruid=8cbbc10b142799170a57036db5630f7ebe9a290f-1696477118
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:48.0) Gecko/20100101 Firefox/50.0
Accept-Encoding: gzip, deflate
 -
[21:38:39 INF] HTTP Response: Redirect - GET - https://sso.garmin.com/sso/login?service=https%3A%2F%2Fconnect.garmin.com%2Fmodern%2F&webhost=https%3A%2F%2Fconnect.garmin.com&gateway=true&generateExtraServiceTicket=true&generateTwoExtraServiceTickets=true&clientId=GarminConnect - Date: Thu, 05 Oct 2023 03:38:39 GMT
Connection: keep-alive
Location: https://connect.garmin.com/modern/
CF-Ray: 8112a209ca9a1f38-DEN
CF-Cache-Status: DYNAMIC
Access-Control-Allow-Origin: https://www.garmin.com
Set-Cookie: org.springframework.web.servlet.i18n.CookieLocaleResolver.LOCALE=en; Path=/, CASTGC=; Max-Age=0; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Path=/; Secure; HttpOnly, CASTGC=; Max-Age=0; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Path=/sso; Secure; HttpOnly, CASRMC=; Max-Age=0; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Path=/; Secure; HttpOnly, CASRMC=; Max-Age=0; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Path=/sso; Secure; HttpOnly, CASMFA=; Max-Age=0; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Path=/; Secure; HttpOnly, CASMFA=; Max-Age=0; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Path=/sso; Secure; HttpOnly, GARMIN-SSO=; Max-Age=0; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Domain=garmin.com; Path=/, GARMIN-SSO=; Max-Age=0; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Domain=garmin.com; Path=/sso, GarminNoCache=; Max-Age=0; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Domain=garmin.com; Path=/, GarminNoCache=; Max-Age=0; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Domain=garmin.com; Path=/sso, GARMIN-SSO-GUID=; Max-Age=0; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Domain=garmin.com; Path=/, GARMIN-SSO-GUID=; Max-Age=0; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Domain=garmin.com; Path=/sso, GARMIN-SSO-CUST-GUID=; Max-Age=0; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Domain=garmin.com; Path=/, GARMIN-SSO-CUST-GUID=; Max-Age=0; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Domain=garmin.com; Path=/sso, GarminBuyCacheKey=; Max-Age=0; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Domain=garmin.com; Path=/, GarminBuyCacheKey=; Max-Age=0; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Domain=garmin.com; Path=/sso
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: Access-Control-Allow-Headers, Origin,Accept, X-Requested-With, Content-Type, Access-Control-Request-Method, Access-Control-Request-Headers
Access-Control-Allow-Methods: GET,POST,OPTIONS
X-Application-Context: casServer:cloud,prod,prod-US_Olathe:1
X-B3-Traceid: 78685d00da4a42125a7bd63241e0c2a6
X-Robots-Tag: noindex
X-Vcap-Request-Id: bb0b258f-bd39-4b84-611d-20a87f57fb4d
Report-To: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=7XwifDRdotdmG3YJ1%2BlItucUs%2Fqj83ypR0%2FueYc5wzMM14kLf0y0eSYvpAFC42MB4Y2LuWLvDs%2BQnIhz69p4Ml2%2FiTTu92ttdT6bA93fwgM4zHRaOgoaPb7FzKkD0l35"}],"group":"cf-nel","max_age":604800}
NEL: {"success_fraction":0.01,"report_to":"cf-nel","max_age":604800}
Vary: Accept-Encoding
Server: cloudflare
 -
[21:38:39 INF] HTTP Request: GET - https://connect.garmin.com/modern/ - Cookie: GARMIN-SSO=1; GarminNoCache=true; GARMIN-SSO-GUID=D260B038F4EFBDA960F51D11BCD1332CB15F2C7B; GARMIN-SSO-CUST-GUID=6338fc67-366e-454e-a6df-0adb72e660a0; __cflb=02DiuJLbVZHipNWxN8yYRX3u8XkAfEE59hivU9zWCH1Zv; _cfuvid=4S_CiCn5IsaBvboWDCAmX4BFie8YyuXxz_ATttStuIM-1696477118926-0-604800000
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:48.0) Gecko/20100101 Firefox/50.0
Accept-Encoding: gzip, deflate
 -
[21:38:39 INF] HTTP Response: Redirect - GET - https://connect.garmin.com/modern/ - Date: Thu, 05 Oct 2023 03:38:38 GMT
Connection: keep-alive
Cache-Control: no-store, must-revalidate, no-cache, max-age=0
Location: https://sso.garmin.com/sso/login?service=https%3A%2F%2Fconnect.garmin.com%2Fmodern%2F&webhost=https%3A%2F%2Fconnect.garmin.com&gateway=true&generateExtraServiceTicket=true&generateTwoExtraServiceTickets=true&clientId=GarminConnectPragma: no-cache
Set-Cookie: ADRUM_BTa=R:0|g:149b6143-8bb4-4b6c-bccb-03ed4169909b; Max-Age=30; Expires=Thu, 05-Oct-2023 03:39:08 GMT; Path=/; Secure, ADRUM_BTa=R:0|g:149b6143-8bb4-4b6c-bccb-03ed4169909b|n:garmin_869629ee-d273-481d-b5a4-f4b0a8c4d5a3; Max-Age=30; Expires=Thu, 05-Oct-2023 03:39:08 GMT; Path=/; Secure, SameSite=None; Max-Age=30; Expires=Thu, 05-Oct-2023 03:39:08 GMT; Path=/; Secure, SESSIONID=YmUzMWU1ZmUtOWJkNS00Yjg1LWFiYWYtZDFjNjk4NmFlMThk; Path=/; Secure; HttpOnly; SameSite=LaxStrict-Transport-Security: max-age=31536000 ; includeSubDomains
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
x-vcap-request-id: ad48d75c-6d2a-4b7f-6153-a815bd5ffbe4
X-XSS-Protection: 1; mode=block
CF-Cache-Status: DYNAMIC
Report-To: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=9%2FDTxNr2ppbTZm0GhBeHkxN0Y2W95djsJ4T8VFdkNxS8n1qay9U3J4emWIDllaOJ2RdumgKyTiVKG3m%2Bku26VdubKjZEimX%2BrC2aeI4m%2BpM9m04TXyzFCl1JataylfCm3NF7rQ%3D%3D"}],"group":"cf-nel","max_age":604800}
NEL: {"success_fraction":0.01,"report_to":"cf-nel","max_age":604800}
Server: cloudflare
CF-RAY: 8112a2095f9a5198-DEN
 -
[21:38:39 INF] HTTP Request: GET - https://connect.garmin.com/?ticket=ST-0179970-D4lRmMGl6fCualkdmOa3-cas - User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:48.0) Gecko/20100101 Firefox/50.0
Cookie: GARMIN-SSO=1; GarminNoCache=true; GARMIN-SSO-GUID=D260B038F4EFBDA960F51D11BCD1332CB15F2C7B; GARMIN-SSO-CUST-GUID=6338fc67-366e-454e-a6df-0adb72e660a0
Accept-Encoding: gzip, deflate
 -
[21:38:39 INF] HTTP Response: Redirect - GET - https://connect.garmin.com/?ticket=ST-0179970-D4lRmMGl6fCualkdmOa3-cas - Date: Thu, 05 Oct 2023 03:38:38 GMT
Connection: keep-alive
Location: /modern/
Cache-Control: no-cache
CF-Cache-Status: DYNAMIC
Report-To: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=bbtxAaMeGdizEMsme8xtHHLfMN25R1h%2BWtaWZtlrUbhN8Ways6dBc7QzUns22e5rNkxHFc84wgaAU9xSulaAJx9lMUfQHqxmgJtXmfTpHPS7f%2BXUpVYd9gwr8wEO2cANFLViFw%3D%3D"}],"group":"cf-nel","max_age":604800}
NEL: {"success_fraction":0.01,"report_to":"cf-nel","max_age":604800}
Set-Cookie: __cflb=02DiuJLbVZHipNWxN8yYRX3u8XkAfEE59hivU9zWCH1Zv; SameSite=None; Secure; path=/; expires=Fri, 06-Oct-23 02:38:38 GMT; HttpOnly, _cfuvid=4S_CiCn5IsaBvboWDCAmX4BFie8YyuXxz_ATttStuIM-1696477118926-0-604800000; path=/; domain=.connect.garmin.com; HttpOnly; Secure; SameSite=None
Server: cloudflare
CF-RAY: 8112a208ff005198-DEN
 -
[21:38:39 ERR] Sync failed to authenticate with Garmin. Auth appeared successful but there was an error sending the service ticket.
Garmin.Auth.GarminAuthenticationError: Auth appeared successful but there was an error sending the service ticket.
 ---> Flurl.Http.FlurlHttpException: Circular redirects detected.
   at Flurl.Http.FlurlRequest.HandleExceptionAsync(FlurlCall call, Exception ex, CancellationToken token)
   at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Garmin.Auth.GarminAuthenticationService.CompleteGarminAuthenticationAsync(String loginResult, GarminApiAuthentication auth) in D:\a\peloton-to-garmin\peloton-to-garmin\src\Garmin\Auth\GarminAuthenticationService.cs:line 174
   --- End of inner exception stack trace ---
   at Garmin.Auth.GarminAuthenticationService.CompleteGarminAuthenticationAsync(String loginResult, GarminApiAuthentication auth) in D:\a\peloton-to-garmin\peloton-to-garmin\src\Garmin\Auth\GarminAuthenticationService.cs:line 181
   at Garmin.Auth.GarminAuthenticationService.RefreshGarminAuthenticationAsync() in D:\a\peloton-to-garmin\peloton-to-garmin\src\Garmin\Auth\GarminAuthenticationService.cs:line 146
   at Garmin.Auth.GarminAuthenticationService.GetGarminAuthenticationAsync() in D:\a\peloton-to-garmin\peloton-to-garmin\src\Garmin\Auth\GarminAuthenticationService.cs:line 70
   at Garmin.GarminUploader.UploadAsync(String[] files, Settings settings) in D:\a\peloton-to-garmin\peloton-to-garmin\src\Garmin\GarminUploader.cs:line 96
   at Garmin.GarminUploader.UploadToGarminAsync() in D:\a\peloton-to-garmin\peloton-to-garmin\src\Garmin\GarminUploader.cs:line 84
   at Sync.SyncService.SyncAsync(IEnumerable`1 workoutIds, ICollection`1 exclude) in D:\a\peloton-to-garmin\peloton-to-garmin\src\Sync\SyncService.cs:line 162
[21:38:39 INF] Done.

```

**Installation (please complete the following information):**
 - OS: [windows]
 - Method: [exe]
 - Version: [3.5.1]

**Additional context**
Had been working. Saw some comments on password with special characters but removed mine by changing password and still saw issue.  

Unsure of next steps to take.

**Comment by philosowaffle** [comment]
duplicate of #526 
Solution is [here](https://github.com/philosowaffle/peloton-to-garmin/issues/526#issuecomment-1742214948).

**Comment by Ficklejam** [comment]
Thank you! This fixed my issue.
