### ISSUE TITLE
Garmin MFA issue

### ISSUE THREAD

**Issue by rod-trent** [philosowaffle/peloton-to-garmin#568]
**Describe the bug**
Looks like Garmin may have altered something about the MFA again. Just today, it started issuing the error posted below.

**To Reproduce**
1. Run the App on Windows
2. Enter MFA code from SMS

**Expected behavior**
n/a

**Logs**
```
Paste Log output here
[10:03:19 INF] HTTP Request: GET - https://connectapi.garmin.com/oauth-service/oauth/preauthorized?ticket=ST-01223945-NC5P0vEp1QIJKNBL1z6c-cas&login-url=https://sso.garmin.com/sso/embed&accepts-mfa-tokens=true - User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 16_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148
Authorization: OAuth oauth_consumer_key="fc3e99d2-118c-44b8-8ae3-03370dde24c0",oauth_nonce="awec3hzmmt8tr7np",oauth_signature="%2B59CHPr%2FCegG2DzLRDL0b0VA3dE%3D",oauth_signature_method="HMAC-SHA1",oauth_timestamp="1701270189",oauth_version="1.0"
Accept-Encoding: gzip, deflate
 -
[10:03:19 INF] HTTP Response: 0 - GET - https://connectapi.garmin.com/oauth-service/oauth/preauthorized?ticket=ST-01223945-NC5P0vEp1QIJKNBL1z6c-cas&login-url=https://sso.garmin.com/sso/embed&accepts-mfa-tokens=true -  -
[10:03:19 FTL] Uncaught Exception
Garmin.Auth.GarminAuthenticationError: Auth appeared successful but failed to get the OAuth1 token.
 ---> Flurl.Http.FlurlHttpTimeoutException: Call timed out: GET https://connectapi.garmin.com/oauth-service/oauth/preauthorized?ticket=ST-01223945-NC5P0vEp1QIJKNBL1z6c-cas&login-url=https://sso.garmin.com/sso/embed&accepts-mfa-tokens=true
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   --- End of inner exception stack trace ---
   at Flurl.Http.FlurlRequest.HandleExceptionAsync(FlurlCall call, Exception ex, CancellationToken token)
   at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Flurl.Http.ResponseExtensions.ReceiveString(Task`1 response)
   at Garmin.Auth.GarminAuthenticationService.GetOAuth1Async(String ticket, GarminApiAuthentication auth, ConsumerCredentials credentials) in D:\a\peloton-to-garmin\peloton-to-garmin\src\Garmin\Auth\GarminAuthenticationService.cs:line 265
   --- End of inner exception stack trace ---
   at Garmin.Auth.GarminAuthenticationService.GetOAuth1Async(String ticket, GarminApiAuthentication auth, ConsumerCredentials credentials) in D:\a\peloton-to-garmin\peloton-to-garmin\src\Garmin\Auth\GarminAuthenticationService.cs:line 268
   at Garmin.Auth.GarminAuthenticationService.CompleteGarminAuthenticationAsync(String loginResult, GarminApiAuthentication auth) in D:\a\peloton-to-garmin\peloton-to-garmin\src\Garmin\Auth\GarminAuthenticationService.cs:line 179
   at Garmin.Auth.GarminAuthenticationService.CompleteMFAAuthAsync(String mfaCode) in D:\a\peloton-to-garmin\peloton-to-garmin\src\Garmin\Auth\GarminAuthenticationService.cs:line 225
   at PelotonToGarminConsole.Startup.RunAsync(CancellationToken cancelToken)

**Installation (please complete the following information):**
 - OS: [Windows]
 - Method: [exe]
 - Version: [3.6.1]

**Additional context**
Add any other context about the problem here.

**Comment by philosowaffle** [comment]
Are you still running into this error?

I tried to reproduce today with my MFA account and did not run into any error.  I was testing on P2G v4, but there shouldn't be any difference between v3.6.1 and v4 in terms of handling MFA.

**Comment by rod-trent** [comment]
It resolved itself after about a day. I'll close this out.
