### ISSUE TITLE
Peloton Email Config Error

### ISSUE THREAD

**Issue by amy26point2** [philosowaffle/peloton-to-garmin#580]
I've gotten a new Mac and I'm reinstalling the source build so I'm not sure if something is going wrong with my install or if this is a new bug. 

**Problem**
Copied over my old config file that worked on the old Mac and also setup as new from a fresh download. Both times I'm getting the error that my Peloton.Email is missing from the config file when it is not. 

2023-12-30 01:40:04.003 -06:00 [INF] *********************************************
2023-12-30 01:40:04.038 -06:00 [INF] P2G Version: p2g_console 4.1.0
2023-12-30 01:40:04.042 -06:00 [INF] Operating System: Unix
2023-12-30 01:40:04.042 -06:00 [INF] OS Version: Unix 14.2.1
2023-12-30 01:40:04.042 -06:00 [INF] DotNet Runtime: 7.0.14
2023-12-30 01:40:04.042 -06:00 [INF] Docker Deployment: false
2023-12-30 01:40:04.043 -06:00 [INF] Config path: /Users/amywenger/Documents/peloton-to-garmin/src/ConsoleClient/configuration.local.json
2023-12-30 01:40:04.043 -06:00 [INF] *********************************************
2023-12-30 01:40:04.045 -06:00 [ERR] Peloton Email required, check your configuration Peloton.Email is set.
2023-12-30 01:40:04.046 -06:00 [ERR] Exception during config validation. Please modify your configuration.local.json and relaunch the application.
System.ArgumentException: Peloton Email must be set. (Parameter 'Email')
   at Peloton.PelotonService.ValidateConfig(PelotonSettings config) in /Users/amywenger/Documents/peloton-to-garmin/src/Peloton/PelotonService.cs:line 68
   at ConsoleClient.Startup.ExecuteAsync(CancellationToken cancelToken) in /Users/amywenger/Documents/peloton-to-garmin/src/ConsoleClient/Startup.cs:line 52
```

**Installation (please complete the following information):**
 - OS: Mac
 - Method: source,
 - Version: 4.1.0

**Comment by philosowaffle** [comment]
Just a sanity check, does this path look correct and point to your config file?

 `Config path: /Users/amywenger/Documents/peloton-to-garmin/src/ConsoleClient/configuration.local.json`

**Comment by philosowaffle** [comment]
Alright, try[ fetching the latest version](https://philosowaffle.github.io/peloton-to-garmin/master/install/source/#updating) of the code again and see if its working now.

**Comment by amy26point2** [comment]
All is right with the world again. Thank you, @philosowaffle !
