### ISSUE TITLE
NativeImplV1 failed to upload workout

### ISSUE THREAD

**Issue by darrenchartier** [philosowaffle/peloton-to-garmin#684]
### Discussed in https://github.com/philosowaffle/peloton-to-garmin/discussions/682

<div type='discussions-op-text'>

<sup>Originally posted by **michaelromero** November 25, 2024</sup>
Was previously uploading workouts fine. Took a few weeks off, and now receiving the following error. Wondering if anyone else is coming across it? I refreshed my peloton and garmin passwords, then updated to the latest p2g version in docker. It read my list of workouts fine, but when I try to upload:

```
2024-11-25 14:32:29 [14:32:29 INF] Found 1 workouts remaining after filtering ExcludedWorkoutTypes.
2024-11-25 14:32:29 [14:32:29 INF] Converting workouts...
2024-11-25 14:32:29 [14:32:29 INF] Uploading workouts to Garmin...
2024-11-25 14:32:29 [14:32:29 INF] Uploading to Garmin: /app/working/upload/74a79e4085bf41899340023931f0f466_30_min_Metallica_Ride_with_Erik_Jäger.fit
2024-11-25 14:32:29 [14:32:29 INF] HTTP Request: POST - https://connectapi.garmin.com/upload-service/upload/.fit - Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImRpLW9hdXRoLXNpZ25lci1wcm9kLTIwMjQtcTEifQ.eyJzY29wZSI6WyJBVFBfUkVBRCIsIkFUUF9XUklURSIsIkNPTU1VTklUWV9DT1VSU0VfUkVBRCIsIkNPTU1VTklUWV9DT1VSU0VfV1JJVEUiLCJDT05ORUNUX1JFQUQiLCJDT05ORUNUX1dSSVRFIiwiRFRfQ0xJRU5UX0FOQUxZVElDU19XUklURSIsIkdBUk1JTlBBWV9SRUFEIiwiR0FSTUlOUEFZX1dSSVRFIiwiR0NPRkZFUl9SRUFEIiwiR0NPRkZFUl9XUklURSIsIkdIU19TQU1EIiwiR0hTX1VQTE9BRCIsIkdPTEZfQVBJX1JFQUQiLCJHT0xGX0FQSV9XUklURSIsIklOU0lHSFRTX1JFQUQiLCJJTlNJR0hUU19XUklURSIsIk9NVF9DQU1QQUlHTl9SRUFEIiwiT01UX1NVQlNDUklQVElPTl9SRUFEIiwiUFJPRFVDVF9TRUFSQ0hfUkVBRCJdLCJpc3MiOiJodHRwczovL2RpYXV0aC5nYXJtaW4uY29tIiwicmV2b2NhdGlvbl9lbGlnaWJpbGl0eSI6WyJHTE9CQUxfU0lHTk9VVCJdLCJjbGllbnRfdHlwZSI6IlVOREVGSU5FRCIsImV4cCI6MTczMjY1MjE0MCwiaWF0IjoxNzMyNTY0MDc5LCJnYXJtaW5fZ3VpZCI6ImYxNzVhMjJiLTg3YzMtNGE3YS1hZTJhLWVlZjQzNmU3MDJmYyIsImp0aSI6ImUwMGJkMDFmLTBmNGUtNDNiZS04YTExLTY4Mzg3OTk4ZDFkNSIsImNsaWVudF9pZCI6IkdBUk1JTl9DT05ORUNUX01PQklMRV9BTkRST0lEX0RJIn0.jr-M8z2TL57HO8JouVZL83xKCavDdJjxmaeInzk6v5ONsrSwwL2aL7D4Y9VfGH3kkAxX3jA0ZABk_1L309RykiQ8Q40V7Kwrz7cx9xvyYY2xNvvkSalyq2i4_XZRlySe34DJjRXY54fuqq-4TCS_sOqAkQNGSeopMjAg55voAubjFxOgqKqF3187_cy54O5HM6cFCxsFY41NfN9QjmMNq8g0HJI-BoaPDkwoqH9n_UNnPs87kPaqAY1Ejq5cbMlXJjSl64aGPHlgCV671XqK9zD6JdC8mYYmHpP7dNbCUBxrj20RAjIkflugQu7PIK7Qt_BTT82-cT6Q3yY-clwkhA
2024-11-25 14:32:29 NK: NT
2024-11-25 14:32:29 Origin: https://sso.garmin.com
2024-11-25 14:32:29 User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 16_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148
2024-11-25 14:32:29 Transfer-Encoding: chunked
2024-11-25 14:32:29 Accept-Encoding: gzip, deflate
2024-11-25 14:32:29 traceparent: 00-6513e4d394f79ceedbe8325f5a9e47fb-9088e372f1cca920-00
2024-11-25 14:32:29  - Flurl.Http.Content.CapturedMultipartContent
2024-11-25 14:32:29 [14:32:29 INF] HTTP Response: 0 - POST - https://connectapi.garmin.com/upload-service/upload/.fit -  - 
2024-11-25 14:32:29 [14:32:29 ERR] Garmin Uploader failed to upload to Garmin Connect. GUpload Exit Code: -1 - NativeImplV1 failed to upload workout /app/working/upload/74a79e4085bf41899340023931f0f466_30_min_Metallica_Ride_with_Erik_Jäger.fit, Call failed. Error while copying content to a stream: POST https://connectapi.garmin.com/upload-service/upload/.fit
2024-11-25 14:32:29 Garmin.GarminUploadException: GUpload Exit Code: -1 - NativeImplV1 failed to upload workout /app/working/upload/74a79e4085bf41899340023931f0f466_30_min_Metallica_Ride_with_Erik_Jäger.fit, Call failed. Error while copying content to a stream: POST https://connectapi.garmin.com/upload-service/upload/.fit
2024-11-25 14:32:29  ---> Flurl.Http.FlurlHttpException: Call failed. Error while copying content to a stream: POST https://connectapi.garmin.com/upload-service/upload/.fit
2024-11-25 14:32:29  ---> System.Net.Http.HttpRequestException: Error while copying content to a stream.
2024-11-25 14:32:29  ---> System.IO.IOException: The response ended prematurely.
2024-11-25 14:32:29    at System.Net.Http.HttpConnection.FillAsync(Boolean async)
2024-11-25 14:32:29    at System.Net.Http.HttpConnection.ChunkedEncodingReadStream.CopyToAsyncCore(Stream destination, CancellationToken cancellationToken)
2024-11-25 14:32:29    at System.IO.Compression.DeflateStream.CopyToStream.CopyFromSourceToDestinationAsync()
2024-11-25 14:32:29    at System.Net.Http.DecompressionHandler.DecompressedContent.SerializeToStreamAsync(Stream stream, TransportContext context, CancellationToken cancellationToken)
2024-11-25 14:32:29    at System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(Task serializeToStreamTask, MemoryStream tempBuffer)
2024-11-25 14:32:29    --- End of inner exception stack trace ---
2024-11-25 14:32:29    at System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(Task serializeToStreamTask, MemoryStream tempBuffer)
2024-11-25 14:32:29    at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
2024-11-25 14:32:29    at Flurl.Http.FlurlClient.SendAsync(IFlurlRequest request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
2024-11-25 14:32:29    --- End of inner exception stack trace ---
2024-11-25 14:32:29    at Flurl.Http.FlurlClient.HandleExceptionAsync(FlurlCall call, Exception ex, CancellationToken token)
2024-11-25 14:32:29    at Flurl.Http.FlurlClient.SendAsync(IFlurlRequest request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
2024-11-25 14:32:29    at Flurl.Http.FlurlClient.SendAsync(IFlurlRequest request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
2024-11-25 14:32:29    at Flurl.Http.ResponseExtensions.ReceiveJson[T](Task`1 response)
2024-11-25 14:32:29    at Garmin.ApiClient.UploadActivity(String filePath, String format, GarminApiAuthentication auth, String userAgent) in /build/src/Garmin/ApiClient.cs:line 124
2024-11-25 14:32:29    at Garmin.GarminUploader.UploadAsync(String[] files, Settings settings) in /build/src/Garmin/GarminUploader.cs:line 102
2024-11-25 14:32:29    --- End of inner exception stack trace ---
2024-11-25 14:32:29    at Garmin.GarminUploader.UploadAsync(String[] files, Settings settings) in /build/src/Garmin/GarminUploader.cs:line 106
2024-11-25 14:32:29    at Garmin.GarminUploader.UploadToGarminAsync() in /build/src/Garmin/GarminUploader.cs:line 74
2024-11-25 14:32:29    at Sync.SyncService.SyncAsync(IEnumerable`1 workoutIds, ICollection`1 exclude) in /build/src/Sync/SyncService.cs:line 171
2024-11-25 14:32:29 info: Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor[1]
2024-11-25 14:32:29       Executing OkObjectResult, writing value of type 'Api.Contract.SyncPostResponse'.
2024-11-25 14:32:29 info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[105]
2024-11-25 14:32:29       Executed action Api.Controllers.SyncController.SyncAsync (Api) in 1766.7962ms
2024-11-25 14:32:29 info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
2024-11-25 14:32:29       Executed endpoint 'Api.Controllers.SyncController.SyncAsync (Api)'
2024-11-25 14:32:29 info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
2024-11-25 14:32:29       Request finished HTTP/1.1 POST http://p2g-api:8080/api/sync application/json;+charset=UTF-8 51 - 200 - application/json;+charset=utf-8 1767.6077ms
``` </div>

**Comment by darrenchartier** [comment]
oops - was already made into #683 dupe - closing
