### ISSUE TITLE
NativeImplV1 failed to upload workout

### ISSUE THREAD

**Issue by betoatx** [philosowaffle/peloton-to-garmin#686]
I get this error when clicking sync in older and latest version:

Errors during sync - GUpload Exit Code: -1 - NativeImplV1 failed to upload workout C:\Users\abcam\Documents\Albert\Garmin\ui_win_4.3.0\working\upload\aab21cea025b41bb9d3b2f7395782da7_30_min_HIIT_&_Hills_Ride_with_Camila_Ramón.fit, Response could not be deserialized to JSON: POST https://connectapi.garmin.com/upload-service/upload/.fit

Then in the logs I get this:

2024-11-26 19:57:33.437 -06:00 [INF] Found 1 workouts remaining after filtering ExcludedWorkoutTypes.
2024-11-26 19:57:33.438 -06:00 [INF] Converting workouts...
2024-11-26 19:57:33.459 -06:00 [INF] Uploading workouts to Garmin...
2024-11-26 19:57:33.460 -06:00 [INF] Uploading to Garmin: C:\Users\username\Documents\Name\Garmin\ui_win_4.3.0\working\upload\aab21cea025b41bb9d3b2f7395782da7_30_min_HIIT_&_Hills_Ride_with_Camila_Ramón.fit
2024-11-26 19:57:33.571 -06:00 [ERR] Http Failed to deserialize response to target type: JSON
Flurl.Http.FlurlParsingException: Response could not be deserialized to JSON: POST https://connectapi.garmin.com/upload-service/upload/.fit
 ---> System.Text.Json.JsonException: The JSON value could not be converted to Garmin.Dto.UploadResponse. Path: $ | LineNumber: 0 | BytePositionInLine: 1.
   at System.Text.Json.ThrowHelper.ThrowJsonException_DeserializeUnableToConvertValue(Type propertyType)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.ContinueDeserialize(ReadBufferState& bufferState, JsonReaderState& jsonReaderState, ReadStack& readStack)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.Deserialize(Stream utf8Json)
   at Flurl.Http.Configuration.DefaultJsonSerializer.Deserialize[T](Stream stream)
   at Flurl.Http.FlurlResponse.GetJsonAsync[T]()
   --- End of inner exception stack trace ---
2024-11-26 19:57:33.571 -06:00 [INF] Response: "OK" - POST - "https://connectapi.garmin.com/upload-service/upload/.fit" - Date: Wed, 27 Nov 2024 01:57:33 GMT

***snip***

2024-11-26 19:57:33.571 -06:00 [ERR] Garmin Uploader failed to upload to Garmin Connect. GUpload Exit Code: -1 - NativeImplV1 failed to upload workout C:\Users\username\Documents\Name\Garmin\ui_win_4.3.0\working\upload\aab21cea025b41bb9d3b2f7395782da7_30_min_HIIT_&_Hills_Ride_with_Camila_Ramón.fit, Response could not be deserialized to JSON: POST https://connectapi.garmin.com/upload-service/upload/.fit
Garmin.GarminUploadException: GUpload Exit Code: -1 - NativeImplV1 failed to upload workout C:\Users\username\Documents\Name\Garmin\ui_win_4.3.0\working\upload\aab21cea025b41bb9d3b2f7395782da7_30_min_HIIT_&_Hills_Ride_with_Camila_Ramón.fit, Response could not be deserialized to JSON: POST https://connectapi.garmin.com/upload-service/upload/.fit
 ---> Flurl.Http.FlurlParsingException: Response could not be deserialized to JSON: POST https://connectapi.garmin.com/upload-service/upload/.fit
 ---> System.Text.Json.JsonException: The JSON value could not be converted to Garmin.Dto.UploadResponse. Path: $ | LineNumber: 0 | BytePositionInLine: 1.
   at System.Text.Json.ThrowHelper.ThrowJsonException_DeserializeUnableToConvertValue(Type propertyType)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.ContinueDeserialize(ReadBufferState& bufferState, JsonReaderState& jsonReaderState, ReadStack& readStack)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.Deserialize(Stream utf8Json)
   at Flurl.Http.Configuration.DefaultJsonSerializer.Deserialize[T](Stream stream)
   at Flurl.Http.FlurlResponse.GetJsonAsync[T]()
   --- End of inner exception stack trace ---
   at Flurl.Http.FlurlClient.HandleExceptionAsync(FlurlCall call, Exception ex, CancellationToken token)
   at Flurl.Http.FlurlResponse.GetJsonAsync[T]()
   at Flurl.Http.ResponseExtensions.ReceiveJson[T](Task`1 response)
   at Garmin.ApiClient.UploadActivity(String filePath, String format, GarminApiAuthentication auth, String userAgent) in D:\a\peloton-to-garmin\peloton-to-garmin\src\Garmin\ApiClient.cs:line 124
   at Garmin.GarminUploader.UploadAsync(String[] files, Settings settings) in D:\a\peloton-to-garmin\peloton-to-garmin\src\Garmin\GarminUploader.cs:line 102
   --- End of inner exception stack trace ---
   at Garmin.GarminUploader.UploadAsync(String[] files, Settings settings) in D:\a\peloton-to-garmin\peloton-to-garmin\src\Garmin\GarminUploader.cs:line 106
   at Garmin.GarminUploader.UploadToGarminAsync() in D:\a\peloton-to-garmin\peloton-to-garmin\src\Garmin\GarminUploader.cs:line 74
   at Sync.SyncService.SyncAsync(IEnumerable`1 workoutIds, ICollection`1 exclude) in D:\a\peloton-to-garmin\peloton-to-garmin\src\Sync\SyncService.cs:line 171

**Comment by gregegan** [comment]
Running into this issue too starting today
